# agent: { description, prefixes }
component_mapping_radio_button_agent = {
    "radio-button-general": { # Nombre de Agente
        "description": "Consultas sobre componente radio-button",
        "prefixes": ["radio-button-interface", "radio-button-definition", "radio-button-usage"] # Nombre de archivos .md a consultar
    },
    "radio-button-template": { # Nombre de Agente
        "description": "Consultas sobre componente radio-button y sus templates",
        "prefixes": ["radio-button-interface", "radio-button-definition", "radio-button-usage", "radio-button-template"] # Nombre de archivos .md a consultar
    },
    "radio-button-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente radio-button",
        "prefixes": ["radio-button-interface", "radio-button-definition", "radio-button-usage", "radio-button-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_radio_button_query = {
    # radio-button-general
    "ilibtbradiobutton": "radio-button-general",
    "libtbradiobuttonmodule": "radio-button-general",
    "lib-tb-radio-button": "radio-button-general",
    "radio button": "radio-button-general",
    "radio-button": "radio-button-general",
    # radio-button-template
    "radio button con template": "radio-button-template",
    "radio button y template": "radio-button-template",
    "radio button + template": "radio-button-template",
    "radio button más template": "radio-button-template",
    "radio button mas template": "radio-button-template",
    "radio button con templates": "radio-button-template",
    "radio button y templates": "radio-button-template",
    "radio button + templates": "radio-button-template",
    "radio button más templates": "radio-button-template",
    "radio button mas templates": "radio-button-template",
    "template y radio button": "radio-button-template",
    "template en radio button": "radio-button-template",
    "template con radio button": "radio-button-template",
    "template de radio button": "radio-button-template",
    "template + radio button": "radio-button-template",
    "template más radio button": "radio-button-template",
    "template mas radio button": "radio-button-template",
    "templates en radio button": "radio-button-template",
    "templates con radio button": "radio-button-template",
    "templates de radio button": "radio-button-template",
    "templates + radio button": "radio-button-template",
    "templates más radio button": "radio-button-template",
    "templates mas radio button": "radio-button-template",
    "radio-button con template": "radio-button-template",
    "radio-button y template": "radio-button-template",
    "radio-button + template": "radio-button-template",
    "radio-button más template": "radio-button-template",
    "radio-button mas template": "radio-button-template",
    "radio-button con templates": "radio-button-template",
    "radio-button y templates": "radio-button-template",
    "radio-button + templates": "radio-button-template",
    "radio-button más templates": "radio-button-template",
    "radio-button mas templates": "radio-button-template",
    "template y radio-button": "radio-button-template",
    "template en radio-button": "radio-button-template",
    "template con radio-button": "radio-button-template",
    "template de radio-button": "radio-button-template",
    "template + radio-button": "radio-button-template",
    "template más radio-button": "radio-button-template",
    "template mas radio-button": "radio-button-template",
    "templates en radio-button": "radio-button-template",
    "templates con radio-button": "radio-button-template",
    "templates de radio-button": "radio-button-template",
    "templates + radio-button": "radio-button-template",
    "templates más radio-button": "radio-button-template",
    "templates mas radio-button": "radio-button-template",
    # radio-button-theme
    "radio button y variables css": "radio-button-theme",
    "radio button y variables css": "radio-button-theme",
    "radio button + variables css": "radio-button-theme",
    "radio button + variables css": "radio-button-theme",
    "radio button mas variables css": "radio-button-theme",
    "radio button mas variables css": "radio-button-theme",
    "radio button más variables css": "radio-button-theme",
    "radio button más variables css": "radio-button-theme",
    "variables css del radio button": "radio-button-theme",
    "variables css del radio button": "radio-button-theme",
    "variables css y radio button": "radio-button-theme",
    "variables css y radio button": "radio-button-theme",
    "variables css + radio button": "radio-button-theme",
    "variables css + radio button": "radio-button-theme",
    "variables css mas radio button": "radio-button-theme",
    "variables css mas radio button": "radio-button-theme",
    "variables css más radio button": "radio-button-theme",
    "variables css más radio button": "radio-button-theme",
    "variables css del componente radio button": "radio-button-theme",
    "variables css del componente radio button": "radio-button-theme",
    "variables css y componente radio button": "radio-button-theme",
    "variables css y componente radio button": "radio-button-theme",
    "variables css + componente radio button": "radio-button-theme",
    "variables css + componente radio button": "radio-button-theme",
    "variables css mas componente radio button": "radio-button-theme",
    "variables css mas componente radio button": "radio-button-theme",
    "variables css más componente radio button": "radio-button-theme",
    "variables css más componente radio button": "radio-button-theme",
    "radio button css variables": "radio-button-theme",
    "radio button component css variables": "radio-button-theme",
    "css variables radio button component": "radio-button-theme",
    "radio button css variables": "radio-button-theme",
    "radio button component css variables": "radio-button-theme",
    "css variables radio button component": "radio-button-theme",
    "radio-button y variables css": "radio-button-theme",
    "radio-button y variables css": "radio-button-theme",
    "radio-button + variables css": "radio-button-theme",
    "radio-button + variables css": "radio-button-theme",
    "radio-button mas variables css": "radio-button-theme",
    "radio-button mas variables css": "radio-button-theme",
    "radio-button más variables css": "radio-button-theme",
    "radio-button más variables css": "radio-button-theme",
    "variables css del radio-button": "radio-button-theme",
    "variables css del radio-button": "radio-button-theme",
    "variables css y radio-button": "radio-button-theme",
    "variables css y radio-button": "radio-button-theme",
    "variables css + radio-button": "radio-button-theme",
    "variables css + radio-button": "radio-button-theme",
    "variables css mas radio-button": "radio-button-theme",
    "variables css mas radio-button": "radio-button-theme",
    "variables css más radio-button": "radio-button-theme",
    "variables css más radio-button": "radio-button-theme",
    "variables css del componente radio-button": "radio-button-theme",
    "variables css del componente radio-button": "radio-button-theme",
    "variables css y componente radio-button": "radio-button-theme",
    "variables css y componente radio-button": "radio-button-theme",
    "variables css + componente radio-button": "radio-button-theme",
    "variables css + componente radio-button": "radio-button-theme",
    "variables css mas componente radio-button": "radio-button-theme",
    "variables css mas componente radio-button": "radio-button-theme",
    "variables css más componente radio-button": "radio-button-theme",
    "variables css más componente radio-button": "radio-button-theme",
    "radio-button css variables": "radio-button-theme",
    "radio-button component css variables": "radio-button-theme",
    "css variables radio-button component": "radio-button-theme",
    "radio-button css variables": "radio-button-theme",
    "radio-button component css variables": "radio-button-theme",
    "css variables radio-button component": "radio-button-theme",
}