# agent: { description, prefixes }
component_mapping_map_agent = {
    "map-general": { # Nombre de Agente
        "description": "Consultas sobre componente map",
        "prefixes": ["map-interface", "map-definition", "map-usage"] # Nombre de archivos .md a consultar
    },
    "map-template": { # Nombre de Agente
        "description": "Consultas sobre componente map y sus templates",
        "prefixes": ["map-interface", "map-definition", "map-usage", "map-template"] # Nombre de archivos .md a consultar
    },
    "map-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente map",
        "prefixes": ["map-interface", "map-definition", "map-usage", "map-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_map_query = {
    # map-general
    "ilibtbmap": "map-general",
    "libtbmapmodule": "map-general",
    "lib-tb-map": "map-general",
    "mapa": "map-general",
    "map": "map-general",
    # map-template
    "mapa con template": "map-template",
    "mapa y template": "map-template",
    "mapa + template": "map-template",
    "mapa más template": "map-template",
    "mapa mas template": "map-template",
    "mapa con templates": "map-template",
    "mapa y templates": "map-template",
    "mapa + templates": "map-template",
    "mapa más templates": "map-template",
    "mapa mas templates": "map-template",
    "template y mapa": "map-template",
    "template en mapa": "map-template",
    "template con mapa": "map-template",
    "template de mapa": "map-template",
    "template + mapa": "map-template",
    "template más mapa": "map-template",
    "template mas mapa": "map-template",
    "templates en mapa": "map-template",
    "templates con mapa": "map-template",
    "templates de mapa": "map-template",
    "templates + mapa": "map-template",
    "templates más mapa": "map-template",
    "templates mas mapa": "map-template",
    "map con template": "map-template",
    "map y template": "map-template",
    "map + template": "map-template",
    "map más template": "map-template",
    "map mas template": "map-template",
    "map con templates": "map-template",
    "map y templates": "map-template",
    "map + templates": "map-template",
    "map más templates": "map-template",
    "map mas templates": "map-template",
    "template en map": "map-template",
    "template con map": "map-template",
    "template de map": "map-template",
    "template + map": "map-template",
    "template más map": "map-template",
    "template mas map": "map-template",
    "templates en map": "map-template",
    "templates con map": "map-template",
    "templates de map": "map-template",
    "templates + map": "map-template",
    "templates más map": "map-template",
    "templates mas map": "map-template",
    # map-theme
    "mapa y variables css": "map-theme",
    "mapa y variables css": "map-theme",
    "mapa + variables css": "map-theme",
    "mapa + variables css": "map-theme",
    "mapa mas variables css": "map-theme",
    "mapa mas variables css": "map-theme",
    "mapa más variables css": "map-theme",
    "mapa más variables css": "map-theme",
    "variables css del mapa": "map-theme",
    "variables css del mapa": "map-theme",
    "variables css y mapa": "map-theme",
    "variables css y mapa": "map-theme",
    "variables css + mapa": "map-theme",
    "variables css + mapa": "map-theme",
    "variables css mas mapa": "map-theme",
    "variables css mas mapa": "map-theme",
    "variables css más mapa": "map-theme",
    "variables css más mapa": "map-theme",
    "variables css del componente mapa": "map-theme",
    "variables css del componente mapa": "map-theme",
    "variables css y componente mapa": "map-theme",
    "variables css y componente mapa": "map-theme",
    "variables css + componente mapa": "map-theme",
    "variables css + componente mapa": "map-theme",
    "variables css mas componente mapa": "map-theme",
    "variables css mas componente mapa": "map-theme",
    "variables css más componente mapa": "map-theme",
    "variables css más componente mapa": "map-theme",
    "map y variables css": "map-theme",
    "map y variables css": "map-theme",
    "map + variables css": "map-theme",
    "map + variables css": "map-theme",
    "map mas variables css": "map-theme",
    "map mas variables css": "map-theme",
    "map más variables css": "map-theme",
    "map más variables css": "map-theme",
    "variables css del map": "map-theme",
    "variables css del map": "map-theme",
    "variables css y map": "map-theme",
    "variables css y map": "map-theme",
    "variables css + map": "map-theme",
    "variables css + map": "map-theme",
    "variables css mas map": "map-theme",
    "variables css mas map": "map-theme",
    "variables css más map": "map-theme",
    "variables css más map": "map-theme",
    "variables css del componente map": "map-theme",
    "variables css del componente map": "map-theme",
    "variables css y componente map": "map-theme",
    "variables css y componente map": "map-theme",
    "variables css + componente map": "map-theme",
    "variables css + componente map": "map-theme",
    "variables css mas componente map": "map-theme",
    "variables css mas componente map": "map-theme",
    "variables css más componente map": "map-theme",
    "variables css más componente map": "map-theme",
    "map css variables": "map-theme",
    "map component css variables": "map-theme",
    "css variables map component": "map-theme",
}