# agent: { description, prefixes }
component_mapping_accordion_agent = {
    "accordion-general": { # Nombre de Agente
        "description": "Consultas sobre componente accordion",
        "prefixes": ["accordion-interface", "accordion-definition", "accordion-usage"] # Nombre de archivos .md a consultar
    },
    "accordion-template": { # Nombre de Agente
        "description": "Consultas sobre componente accordion y sus templates",
        "prefixes": ["accordion-interface", "accordion-definition", "accordion-usage", "accordion-template"] # Nombre de archivos .md a consultar
    },
    "accordion-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente accordion",
        "prefixes": ["accordion-interface", "accordion-definition", "accordion-usage", "accordion-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_accordion_query = {
    # accordion-general
    "ilibtbaccordion": "accordion-general",
    "ilibtbaccordiontab": "accordion-general",
    "libtbaccordionmodule": "accordion-general",
    "lib-tb-accordion": "accordion-general",
    "acordeon": "accordion-general",
    "acordeón": "accordion-general",
    "accordion": "accordion-general",
    # accordion-template
    "acordeon con template": "accordion-template",
    "acordeon y template": "accordion-template",
    "acordeon + template": "accordion-template",
    "acordeon más template": "accordion-template",
    "acordeon mas template": "accordion-template",
    "acordeon con templates": "accordion-template",
    "acordeon y templates": "accordion-template",
    "acordeon + templates": "accordion-template",
    "acordeon más templates": "accordion-template",
    "acordeon mas templates": "accordion-template",
    "template y acordeon": "accordion-template",
    "template en acordeon": "accordion-template",
    "template con acordeon": "accordion-template",
    "template de acordeon": "accordion-template",
    "template + acordeon": "accordion-template",
    "template más acordeon": "accordion-template",
    "template mas acordeon": "accordion-template",
    "templates en acordeon": "accordion-template",
    "templates con acordeon": "accordion-template",
    "templates de acordeon": "accordion-template",
    "templates + acordeon": "accordion-template",
    "templates más acordeon": "accordion-template",
    "templates mas acordeon": "accordion-template",
    "acordeón con template": "accordion-template",
    "acordeón y template": "accordion-template",
    "acordeón + template": "accordion-template",
    "acordeón más template": "accordion-template",
    "acordeón mas template": "accordion-template",
    "acordeón con templates": "accordion-template",
    "acordeón y templates": "accordion-template",
    "acordeón + templates": "accordion-template",
    "acordeón más templates": "accordion-template",
    "acordeón mas templates": "accordion-template",
    "template y acordeón": "accordion-template",
    "template en acordeón": "accordion-template",
    "template con acordeón": "accordion-template",
    "template de acordeón": "accordion-template",
    "template + acordeón": "accordion-template",
    "template más acordeón": "accordion-template",
    "template mas acordeón": "accordion-template",
    "templates en acordeón": "accordion-template",
    "templates con acordeón": "accordion-template",
    "templates de acordeón": "accordion-template",
    "templates + acordeón": "accordion-template",
    "templates más acordeón": "accordion-template",
    "templates mas acordeón": "accordion-template",
    "accordion con template": "accordion-template",
    "accordion y template": "accordion-template",
    "accordion + template": "accordion-template",
    "accordion más template": "accordion-template",
    "accordion mas template": "accordion-template",
    "accordion con templates": "accordion-template",
    "accordion y templates": "accordion-template",
    "accordion + templates": "accordion-template",
    "accordion más templates": "accordion-template",
    "accordion mas templates": "accordion-template",
    "template en accordion": "accordion-template",
    "template con accordion": "accordion-template",
    "template de accordion": "accordion-template",
    "template + accordion": "accordion-template",
    "template más accordion": "accordion-template",
    "template mas accordion": "accordion-template",
    "templates en accordion": "accordion-template",
    "templates con accordion": "accordion-template",
    "templates de accordion": "accordion-template",
    "templates + accordion": "accordion-template",
    "templates más accordion": "accordion-template",
    "templates mas accordion": "accordion-template",
    # accordion-theme
    "acordeon y variables css": "accordion-theme",
    "acordeon y variables css": "accordion-theme",
    "acordeon + variables css": "accordion-theme",
    "acordeon + variables css": "accordion-theme",
    "acordeon mas variables css": "accordion-theme",
    "acordeon mas variables css": "accordion-theme",
    "acordeon más variables css": "accordion-theme",
    "acordeon más variables css": "accordion-theme",
    "variables css de la acordeon": "accordion-theme",
    "variables css de la acordeon": "accordion-theme",
    "variables css y acordeon": "accordion-theme",
    "variables css y acordeon": "accordion-theme",
    "variables css + acordeon": "accordion-theme",
    "variables css + acordeon": "accordion-theme",
    "variables css mas acordeon": "accordion-theme",
    "variables css mas acordeon": "accordion-theme",
    "variables css más acordeon": "accordion-theme",
    "variables css más acordeon": "accordion-theme",
    "variables css del componente acordeon": "accordion-theme",
    "variables css del componente acordeon": "accordion-theme",
    "variables css y componente acordeon": "accordion-theme",
    "variables css y componente acordeon": "accordion-theme",
    "variables css + componente acordeon": "accordion-theme",
    "variables css + componente acordeon": "accordion-theme",
    "variables css mas componente acordeon": "accordion-theme",
    "variables css mas componente acordeon": "accordion-theme",
    "variables css más componente acordeon": "accordion-theme",
    "variables css más componente acordeon": "accordion-theme",
    "acordeón y variables css": "accordion-theme",
    "acordeón y variables css": "accordion-theme",
    "acordeón + variables css": "accordion-theme",
    "acordeón + variables css": "accordion-theme",
    "acordeón mas variables css": "accordion-theme",
    "acordeón mas variables css": "accordion-theme",
    "acordeón más variables css": "accordion-theme",
    "acordeón más variables css": "accordion-theme",
    "variables css de la acordeón": "accordion-theme",
    "variables css de la acordeón": "accordion-theme",
    "variables css y acordeón": "accordion-theme",
    "variables css y acordeón": "accordion-theme",
    "variables css + acordeón": "accordion-theme",
    "variables css + acordeón": "accordion-theme",
    "variables css mas acordeón": "accordion-theme",
    "variables css mas acordeón": "accordion-theme",
    "variables css más acordeón": "accordion-theme",
    "variables css más acordeón": "accordion-theme",
    "variables css del componente acordeón": "accordion-theme",
    "variables css del componente acordeón": "accordion-theme",
    "variables css y componente acordeón": "accordion-theme",
    "variables css y componente acordeón": "accordion-theme",
    "variables css + componente acordeón": "accordion-theme",
    "variables css + componente acordeón": "accordion-theme",
    "variables css mas componente acordeón": "accordion-theme",
    "variables css mas componente acordeón": "accordion-theme",
    "variables css más componente acordeón": "accordion-theme",
    "variables css más componente acordeón": "accordion-theme",
    "accordion y variables css": "accordion-theme",
    "accordion y variables css": "accordion-theme",
    "accordion + variables css": "accordion-theme",
    "accordion + variables css": "accordion-theme",
    "accordion mas variables css": "accordion-theme",
    "accordion mas variables css": "accordion-theme",
    "accordion más variables css": "accordion-theme",
    "accordion más variables css": "accordion-theme",
    "variables css del accordion": "accordion-theme",
    "variables css del accordion": "accordion-theme",
    "variables css y accordion": "accordion-theme",
    "variables css y accordion": "accordion-theme",
    "variables css + accordion": "accordion-theme",
    "variables css + accordion": "accordion-theme",
    "variables css mas accordion": "accordion-theme",
    "variables css mas accordion": "accordion-theme",
    "variables css más accordion": "accordion-theme",
    "variables css más accordion": "accordion-theme",
    "variables css del componente accordion": "accordion-theme",
    "variables css del componente accordion": "accordion-theme",
    "variables css y componente accordion": "accordion-theme",
    "variables css y componente accordion": "accordion-theme",
    "variables css + componente accordion": "accordion-theme",
    "variables css + componente accordion": "accordion-theme",
    "variables css mas componente accordion": "accordion-theme",
    "variables css mas componente accordion": "accordion-theme",
    "variables css más componente accordion": "accordion-theme",
    "variables css más componente accordion": "accordion-theme",
    "accordion css variables": "accordion-theme",
    "accordion component css variables": "accordion-theme",
    "css variables accordion component": "accordion-theme",
}