# agent: { description, prefixes }
component_mapping_stepper_vertical_agent = {
    "stepper-vertical-general": { # Nombre de Agente
        "description": "Consultas sobre componente stepper-vertical",
        "prefixes": ["stepper-vertical-interface", "stepper-vertical-definition", "stepper-vertical-usage"] # Nombre de archivos .md a consultar
    },
    "stepper-vertical-template": { # Nombre de Agente
        "description": "Consultas sobre componente stepper-vertical y sus templates",
        "prefixes": ["stepper-vertical-interface", "stepper-vertical-definition", "stepper-vertical-usage", "stepper-vertical-template"] # Nombre de archivos .md a consultar
    },
    "stepper-vertical-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente stepper-vertical",
        "prefixes": ["stepper-vertical-interface", "stepper-vertical-definition", "stepper-vertical-usage", "stepper-vertical-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_stepper_vertical_query = {
    # stepper-vertical-general
    "ilibtbsteppervertical": "stepper-vertical-general",
    "libtbstepperverticalmodule": "stepper-vertical-general",
    "lib-tb-stepper-vertical": "stepper-vertical-general",
    "stepper vertical": "stepper-vertical-general",
    "vertical stepper": "stepper-vertical-general",
    "stepper-vertical": "stepper-vertical-general",
    # stepper-vertical-template
    "stepper-vertical con template": "stepper-vertical-template",
    "stepper-vertical y template": "stepper-vertical-template",
    "stepper-vertical + template": "stepper-vertical-template",
    "stepper-vertical más template": "stepper-vertical-template",
    "stepper-vertical mas template": "stepper-vertical-template",
    "stepper-vertical con templates": "stepper-vertical-template",
    "stepper-vertical y templates": "stepper-vertical-template",
    "stepper-vertical + templates": "stepper-vertical-template",
    "stepper-vertical más templates": "stepper-vertical-template",
    "stepper-vertical mas templates": "stepper-vertical-template",
    "template y stepper-vertical": "stepper-vertical-template",
    "template en stepper-vertical": "stepper-vertical-template",
    "template con stepper-vertical": "stepper-vertical-template",
    "template de stepper-vertical": "stepper-vertical-template",
    "template + stepper-vertical": "stepper-vertical-template",
    "template más stepper-vertical": "stepper-vertical-template",
    "template mas stepper-vertical": "stepper-vertical-template",
    "templates y stepper-vertical": "stepper-vertical-template",
    "templates en stepper-vertical": "stepper-vertical-template",
    "templates con stepper-vertical": "stepper-vertical-template",
    "templates de stepper-vertical": "stepper-vertical-template",
    "templates + stepper-vertical": "stepper-vertical-template",
    "templates más stepper-vertical": "stepper-vertical-template",
    "templates mas stepper-vertical": "stepper-vertical-template",
    "stepper vertical con template": "stepper-vertical-template",
    "stepper vertical y template": "stepper-vertical-template",
    "stepper vertical + template": "stepper-vertical-template",
    "stepper vertical más template": "stepper-vertical-template",
    "stepper vertical mas template": "stepper-vertical-template",
    "stepper vertical con templates": "stepper-vertical-template",
    "stepper vertical y templates": "stepper-vertical-template",
    "stepper vertical + templates": "stepper-vertical-template",
    "stepper vertical más templates": "stepper-vertical-template",
    "stepper vertical mas templates": "stepper-vertical-template",
    "template y stepper vertical": "stepper-vertical-template",
    "template en stepper vertical": "stepper-vertical-template",
    "template con stepper vertical": "stepper-vertical-template",
    "template de stepper vertical": "stepper-vertical-template",
    "template del stepper vertical": "stepper-vertical-template",
    "template + stepper vertical": "stepper-vertical-template",
    "template más stepper vertical": "stepper-vertical-template",
    "template mas stepper vertical": "stepper-vertical-template",
    "templates y stepper vertical": "stepper-vertical-template",
    "templates en stepper vertical": "stepper-vertical-template",
    "templates con stepper vertical": "stepper-vertical-template",
    "templates de stepper vertical": "stepper-vertical-template",
    "templates del stepper vertical": "stepper-vertical-template",
    "templates + stepper vertical": "stepper-vertical-template",
    "templates más stepper vertical": "stepper-vertical-template",
    "templates mas stepper vertical": "stepper-vertical-template",
    "vertical stepper con template": "stepper-vertical-template",
    "vertical stepper y template": "stepper-vertical-template",
    "vertical stepper + template": "stepper-vertical-template",
    "vertical stepper más template": "stepper-vertical-template",
    "vertical stepper mas template": "stepper-vertical-template",
    "vertical stepper con templates": "stepper-vertical-template",
    "vertical stepper y templates": "stepper-vertical-template",
    "vertical stepper + templates": "stepper-vertical-template",
    "vertical stepper más templates": "stepper-vertical-template",
    "vertical stepper mas templates": "stepper-vertical-template",
    "template y vertical stepper": "stepper-vertical-template",
    "template en vertical stepper": "stepper-vertical-template",
    "template con vertical stepper": "stepper-vertical-template",
    "template de vertical stepper": "stepper-vertical-template",
    "template del vertical stepper": "stepper-vertical-template",
    "template + vertical stepper": "stepper-vertical-template",
    "template más vertical stepper": "stepper-vertical-template",
    "template mas vertical stepper": "stepper-vertical-template",
    "templates y vertical stepper": "stepper-vertical-template",
    "templates en vertical stepper": "stepper-vertical-template",
    "templates con vertical stepper": "stepper-vertical-template",
    "templates de vertical stepper": "stepper-vertical-template",
    "templates del vertical stepper": "stepper-vertical-template",
    "templates + vertical stepper": "stepper-vertical-template",
    "templates más vertical stepper": "stepper-vertical-template",
    "templates mas vertical stepper": "stepper-vertical-template",
    # stepper-vertical-theme
    "stepper vertical y variables css": "stepper-vertical-theme",
    "stepper-vertical y variables css": "stepper-vertical-theme",
    "stepper vertical + variables css": "stepper-vertical-theme",
    "stepper-vertical + variables css": "stepper-vertical-theme",
    "stepper vertical mas variables css": "stepper-vertical-theme",
    "stepper-vertical mas variables css": "stepper-vertical-theme",
    "stepper vertical más variables css": "stepper-vertical-theme",
    "stepper-vertical más variables css": "stepper-vertical-theme",
    "variables css del stepper vertical": "stepper-vertical-theme",
    "variables css del stepper-vertical": "stepper-vertical-theme",
    "variables css y stepper vertical": "stepper-vertical-theme",
    "variables css y stepper-vertical": "stepper-vertical-theme",
    "variables css + stepper vertical": "stepper-vertical-theme",
    "variables css + stepper-vertical": "stepper-vertical-theme",
    "variables css mas stepper vertical": "stepper-vertical-theme",
    "variables css mas stepper-vertical": "stepper-vertical-theme",
    "variables css más stepper vertical": "stepper-vertical-theme",
    "variables css más stepper-vertical": "stepper-vertical-theme",
    "variables css del componente stepper vertical": "stepper-vertical-theme",
    "variables css del componente stepper-vertical": "stepper-vertical-theme",
    "variables css y componente stepper vertical": "stepper-vertical-theme",
    "variables css y componente stepper-vertical": "stepper-vertical-theme",
    "variables css + componente stepper vertical": "stepper-vertical-theme",
    "variables css + componente stepper-vertical": "stepper-vertical-theme",
    "variables css mas componente stepper vertical": "stepper-vertical-theme",
    "variables css mas componente stepper-vertical": "stepper-vertical-theme",
    "variables css más componente stepper vertical": "stepper-vertical-theme",
    "variables css más componente stepper-vertical": "stepper-vertical-theme",
    "vertical stepper y variables css": "stepper-vertical-theme",
    "vertical stepper + variables css": "stepper-vertical-theme",
    "vertical stepper mas variables css": "stepper-vertical-theme",
    "vertical stepper más variables css": "stepper-vertical-theme",
    "variables css del vertical stepper": "stepper-vertical-theme",
    "variables css y vertical stepper": "stepper-vertical-theme",
    "variables css + vertical stepper": "stepper-vertical-theme",
    "variables css mas vertical stepper": "stepper-vertical-theme",
    "variables css más vertical stepper": "stepper-vertical-theme",
    "variables css del componente vertical stepper": "stepper-vertical-theme",
    "variables css y componente vertical stepper": "stepper-vertical-theme",
    "variables css + componente vertical stepper": "stepper-vertical-theme",
    "variables css mas componente vertical stepper": "stepper-vertical-theme",
    "variables css más componente vertical stepper": "stepper-vertical-theme",
    "stepper vertical css variables": "stepper-vertical-theme",
    "vertical stepper css variables": "stepper-vertical-theme",
    "stepper vertical component css variables": "stepper-vertical-theme",
    "vertical stepper component css variables": "stepper-vertical-theme",
    "css variables vertical stepper component": "stepper-vertical-theme",
    "css variables vertical stepper component": "stepper-vertical-theme",
    "stepper-vertical css variables": "stepper-vertical-theme",
    "stepper-vertical component css variables": "stepper-vertical-theme",
    "css variables stepper-vertical component": "stepper-vertical-theme",
}