# agent: { description, prefixes }
component_mapping_uploading_file_agent = {
    "uploading-file-general": { # Nombre de Agente
        "description": "Consultas sobre componente uploading-file",
        "prefixes": ["uploading-file-interface", "uploading-file-definition", "uploading-file-usage"] # Nombre de archivos .md a consultar
    },
    "uploading-file-template": { # Nombre de Agente
        "description": "Consultas sobre componente uploading-file y sus templates",
        "prefixes": ["uploading-file-interface", "uploading-file-definition", "uploading-file-usage", "uploading-file-template"] # Nombre de archivos .md a consultar
    },
    "uploading-file-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente uploading-file",
        "prefixes": ["uploading-file-interface", "uploading-file-definition", "uploading-file-usage", "uploading-file-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_uploading_file_query = {
    # uploading-file-general
    "ilibtbuploadingfile": "uploading-file-general",
    "libtbuploadingfilemodule": "uploading-file-general",
    "lib-tb-uploading-file": "uploading-file-general",
    "uploading file": "uploading-file-general",
    "uploading-file": "uploading-file-general",
    # uploading-file-template
    "uploading-file con template": "uploading-file-template",
    "uploading-file y template": "uploading-file-template",
    "uploading-file + template": "uploading-file-template",
    "uploading-file más template": "uploading-file-template",
    "uploading-file mas template": "uploading-file-template",
    "uploading-file con templates": "uploading-file-template",
    "uploading-file y templates": "uploading-file-template",
    "uploading-file + templates": "uploading-file-template",
    "uploading-file más templates": "uploading-file-template",
    "uploading-file mas templates": "uploading-file-template",
    "template en uploading-file": "uploading-file-template",
    "template con uploading-file": "uploading-file-template",
    "template de uploading-file": "uploading-file-template",
    "template + uploading-file": "uploading-file-template",
    "template más uploading-file": "uploading-file-template",
    "template mas uploading-file": "uploading-file-template",
    "templates en uploading-file": "uploading-file-template",
    "templates con uploading-file": "uploading-file-template",
    "templates de uploading-file": "uploading-file-template",
    "templates + uploading-file": "uploading-file-template",
    "templates más uploading-file": "uploading-file-template",
    "templates mas uploading-file": "uploading-file-template",
    "uploading file con template": "uploading-file-template",
    "uploading file y template": "uploading-file-template",
    "uploading file + template": "uploading-file-template",
    "uploading file más template": "uploading-file-template",
    "uploading file mas template": "uploading-file-template",
    "uploading file con templates": "uploading-file-template",
    "uploading file y templates": "uploading-file-template",
    "uploading file + templates": "uploading-file-template",
    "uploading file más templates": "uploading-file-template",
    "uploading file mas templates": "uploading-file-template",
    "template en uploading file": "uploading-file-template",
    "template con uploading file": "uploading-file-template",
    "template de uploading file": "uploading-file-template",
    "template del uploading file": "uploading-file-template",
    "template + uploading file": "uploading-file-template",
    "template más uploading file": "uploading-file-template",
    "template mas uploading file": "uploading-file-template",
    "templates en uploading file": "uploading-file-template",
    "templates con uploading file": "uploading-file-template",
    "templates de uploading file": "uploading-file-template",
    "templates del uploading file": "uploading-file-template",
    "templates + uploading file": "uploading-file-template",
    "templates más uploading file": "uploading-file-template",
    "templates mas uploading file": "uploading-file-template",
    # uploading-file-theme
    "uploading file y variables css": "uploading-file-theme",
    "uploading-file y variables css": "uploading-file-theme",
    "uploading file + variables css": "uploading-file-theme",
    "uploading-file + variables css": "uploading-file-theme",
    "uploading file mas variables css": "uploading-file-theme",
    "uploading-file mas variables css": "uploading-file-theme",
    "uploading file más variables css": "uploading-file-theme",
    "uploading-file más variables css": "uploading-file-theme",
    "variables css del uploading file": "uploading-file-theme",
    "variables css del uploading-file": "uploading-file-theme",
    "variables css y uploading file": "uploading-file-theme",
    "variables css y uploading-file": "uploading-file-theme",
    "variables css + uploading file": "uploading-file-theme",
    "variables css + uploading-file": "uploading-file-theme",
    "variables css mas uploading file": "uploading-file-theme",
    "variables css mas uploading-file": "uploading-file-theme",
    "variables css más uploading file": "uploading-file-theme",
    "variables css más uploading-file": "uploading-file-theme",
    "variables css del componente uploading file": "uploading-file-theme",
    "variables css del componente uploading-file": "uploading-file-theme",
    "variables css y componente uploading file": "uploading-file-theme",
    "variables css y componente uploading-file": "uploading-file-theme",
    "variables css + componente uploading file": "uploading-file-theme",
    "variables css + componente uploading-file": "uploading-file-theme",
    "variables css mas componente uploading file": "uploading-file-theme",
    "variables css mas componente uploading-file": "uploading-file-theme",
    "variables css más componente uploading file": "uploading-file-theme",
    "variables css más componente uploading-file": "uploading-file-theme",
    "uploading file css variables": "uploading-file-theme",
    "uploading file component css variables": "uploading-file-theme",
    "css variables uploading file component": "uploading-file-theme",
    "uploading-file css variables": "uploading-file-theme",
    "uploading-file component css variables": "uploading-file-theme",
    "css variables uploading-file component": "uploading-file-theme",
}