# agent: { description, prefixes }
component_mapping_empty_message_agent = {
    "empty-message-general": { # Nombre de Agente
        "description": "Consultas sobre componente empty-message",
        "prefixes": ["empty-message-interface", "empty-message-definition", "empty-message-usage"] # Nombre de archivos .md a consultar
    },
    "empty-message-template": { # Nombre de Agente
        "description": "Consultas sobre componente empty-message y sus templates",
        "prefixes": ["empty-message-interface", "empty-message-definition", "empty-message-usage", "empty-message-template"] # Nombre de archivos .md a consultar
    },
    "empty-message-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente empty-message",
        "prefixes": ["empty-message-interface", "empty-message-definition", "empty-message-usage", "empty-message-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_empty_message_query = {
    # empty-message-general
    "ilibtbemptymessage": "empty-message-general",
    "libtbemptymessagemodule": "empty-message-general",
    "lib-tb-empty-message": "empty-message-general",
    "empty message": "empty-message-general",
    "empty-message": "empty-message-general",
    # empty-message-template
    "empty-message con template": "empty-message-template",
    "empty-message y template": "empty-message-template",
    "empty-message + template": "empty-message-template",
    "empty-message más template": "empty-message-template",
    "empty-message mas template": "empty-message-template",
    "empty-message con templates": "empty-message-template",
    "empty-message y templates": "empty-message-template",
    "empty-message + templates": "empty-message-template",
    "empty-message más templates": "empty-message-template",
    "empty-message mas templates": "empty-message-template",
    "template en empty-message": "empty-message-template",
    "template con empty-message": "empty-message-template",
    "template de empty-message": "empty-message-template",
    "template + empty-message": "empty-message-template",
    "template más empty-message": "empty-message-template",
    "template mas empty-message": "empty-message-template",
    "templates en empty-message": "empty-message-template",
    "templates con empty-message": "empty-message-template",
    "templates de empty-message": "empty-message-template",
    "templates + empty-message": "empty-message-template",
    "templates más empty-message": "empty-message-template",
    "templates mas empty-message": "empty-message-template",
    "empty message con template": "empty-message-template",
    "empty message y template": "empty-message-template",
    "empty message + template": "empty-message-template",
    "empty message más template": "empty-message-template",
    "empty message mas template": "empty-message-template",
    "empty message con templates": "empty-message-template",
    "empty message y templates": "empty-message-template",
    "empty message + templates": "empty-message-template",
    "empty message más templates": "empty-message-template",
    "empty message mas templates": "empty-message-template",
    "template en empty message": "empty-message-template",
    "template con empty message": "empty-message-template",
    "template de empty message": "empty-message-template",
    "template del empty message": "empty-message-template",
    "template + empty message": "empty-message-template",
    "template más empty message": "empty-message-template",
    "template mas empty message": "empty-message-template",
    "templates en empty message": "empty-message-template",
    "templates con empty message": "empty-message-template",
    "templates de empty message": "empty-message-template",
    "templates del empty message": "empty-message-template",
    "templates + empty message": "empty-message-template",
    "templates más empty message": "empty-message-template",
    "templates mas empty message": "empty-message-template",
    # empty-message-theme
    "empty message y variables css": "empty-message-theme",
    "empty-message y variables css": "empty-message-theme",
    "empty message + variables css": "empty-message-theme",
    "empty-message + variables css": "empty-message-theme",
    "empty message mas variables css": "empty-message-theme",
    "empty-message mas variables css": "empty-message-theme",
    "empty message más variables css": "empty-message-theme",
    "empty-message más variables css": "empty-message-theme",
    "variables css del empty message": "empty-message-theme",
    "variables css del empty-message": "empty-message-theme",
    "variables css y empty message": "empty-message-theme",
    "variables css y empty-message": "empty-message-theme",
    "variables css + empty message": "empty-message-theme",
    "variables css + empty-message": "empty-message-theme",
    "variables css mas empty message": "empty-message-theme",
    "variables css mas empty-message": "empty-message-theme",
    "variables css más empty message": "empty-message-theme",
    "variables css más empty-message": "empty-message-theme",
    "variables css del componente empty message": "empty-message-theme",
    "variables css del componente empty-message": "empty-message-theme",
    "variables css y componente empty message": "empty-message-theme",
    "variables css y componente empty-message": "empty-message-theme",
    "variables css + componente empty message": "empty-message-theme",
    "variables css + componente empty-message": "empty-message-theme",
    "variables css mas componente empty message": "empty-message-theme",
    "variables css mas componente empty-message": "empty-message-theme",
    "variables css más componente empty message": "empty-message-theme",
    "variables css más componente empty-message": "empty-message-theme",
    "empty message css variables": "empty-message-theme",
    "empty message component css variables": "empty-message-theme",
    "css variables empty message component": "empty-message-theme",
    "empty-message css variables": "empty-message-theme",
    "empty-message component css variables": "empty-message-theme",
    "css variables empty-message component": "empty-message-theme",
}