# agent: { description, prefixes }
component_mapping_progress_spinner_agent = {
    "progress-spinner-general": { # Nombre de Agente
        "description": "Consultas sobre componente progress-spinner",
        "prefixes": ["progress-spinner-interface", "progress-spinner-definition", "progress-spinner-usage"] # Nombre de archivos .md a consultar
    },
    "progress-spinner-template": { # Nombre de Agente
        "description": "Consultas sobre componente progress-spinner y sus templates",
        "prefixes": ["progress-spinner-interface", "progress-spinner-definition", "progress-spinner-usage", "progress-spinner-template"] # Nombre de archivos .md a consultar
    },
    "progress-spinner-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente progress-spinner",
        "prefixes": ["progress-spinner-interface", "progress-spinner-definition", "progress-spinner-usage", "progress-spinner-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_progress_spinner_query = {
    # progress-spinner-general
    "ilibtbprogressspinner": "progress-spinner-general",
    "libtbprogressspinnermodule": "progress-spinner-general",
    "lib-tb-progress-spinner": "progress-spinner-general",
    "cargando": "progress-spinner-general",
    "loading": "progress-spinner-general",
    "progress spinner": "progress-spinner-general",
    "progress-spinner": "progress-spinner-general",
    # progress-spinner-template
    "cargando con template": "progress-spinner-template",
    "cargando y template": "progress-spinner-template",
    "cargando + template": "progress-spinner-template",
    "cargando más template": "progress-spinner-template",
    "cargando mas template": "progress-spinner-template",
    "cargando con templates": "progress-spinner-template",
    "cargando y templates": "progress-spinner-template",
    "cargando + templates": "progress-spinner-template",
    "cargando más templates": "progress-spinner-template",
    "cargando mas templates": "progress-spinner-template",
    "template y cargando": "progress-spinner-template",
    "template en cargando": "progress-spinner-template",
    "template con cargando": "progress-spinner-template",
    "template de cargando": "progress-spinner-template",
    "template de la cargando": "progress-spinner-template",
    "template + cargando": "progress-spinner-template",
    "template más cargando": "progress-spinner-template",
    "template mas cargando": "progress-spinner-template",
    "templates en cargando": "progress-spinner-template",
    "templates con cargando": "progress-spinner-template",
    "templates de la cargando": "progress-spinner-template",
    "templates + cargando": "progress-spinner-template",
    "templates más cargando": "progress-spinner-template",
    "templates mas cargando": "progress-spinner-template",
    "loading con template": "progress-spinner-template",
    "loading y template": "progress-spinner-template",
    "loading + template": "progress-spinner-template",
    "loading más template": "progress-spinner-template",
    "loading mas template": "progress-spinner-template",
    "loading con templates": "progress-spinner-template",
    "loading y templates": "progress-spinner-template",
    "loading + templates": "progress-spinner-template",
    "loading más templates": "progress-spinner-template",
    "loading mas templates": "progress-spinner-template",
    "template y loading": "progress-spinner-template",
    "template en loading": "progress-spinner-template",
    "template con loading": "progress-spinner-template",
    "template de loading": "progress-spinner-template",
    "template del loading": "progress-spinner-template",
    "template + loading": "progress-spinner-template",
    "template más loading": "progress-spinner-template",
    "template mas loading": "progress-spinner-template",
    "templates en loading": "progress-spinner-template",
    "templates con loading": "progress-spinner-template",
    "templates de loading": "progress-spinner-template",
    "templates del loading": "progress-spinner-template",
    "templates + loading": "progress-spinner-template",
    "templates más loading": "progress-spinner-template",
    "templates mas loading": "progress-spinner-template",
    "progress-spinner con template": "progress-spinner-template",
    "progress-spinner y template": "progress-spinner-template",
    "progress-spinner + template": "progress-spinner-template",
    "progress-spinner más template": "progress-spinner-template",
    "progress-spinner mas template": "progress-spinner-template",
    "progress-spinner con templates": "progress-spinner-template",
    "progress-spinner y templates": "progress-spinner-template",
    "progress-spinner + templates": "progress-spinner-template",
    "progress-spinner más templates": "progress-spinner-template",
    "progress-spinner mas templates": "progress-spinner-template",
    "template en progress-spinner": "progress-spinner-template",
    "template con progress-spinner": "progress-spinner-template",
    "template de progress-spinner": "progress-spinner-template",
    "template + progress-spinner": "progress-spinner-template",
    "template más progress-spinner": "progress-spinner-template",
    "template mas progress-spinner": "progress-spinner-template",
    "templates en progress-spinner": "progress-spinner-template",
    "templates con progress-spinner": "progress-spinner-template",
    "templates de progress-spinner": "progress-spinner-template",
    "templates + progress-spinner": "progress-spinner-template",
    "templates más progress-spinner": "progress-spinner-template",
    "templates mas progress-spinner": "progress-spinner-template",
    "progress spinner con template": "progress-spinner-template",
    "progress spinner y template": "progress-spinner-template",
    "progress spinner + template": "progress-spinner-template",
    "progress spinner más template": "progress-spinner-template",
    "progress spinner mas template": "progress-spinner-template",
    "progress spinner con templates": "progress-spinner-template",
    "progress spinner y templates": "progress-spinner-template",
    "progress spinner + templates": "progress-spinner-template",
    "progress spinner más templates": "progress-spinner-template",
    "progress spinner mas templates": "progress-spinner-template",
    "template en progress spinner": "progress-spinner-template",
    "template con progress spinner": "progress-spinner-template",
    "template de progress spinner": "progress-spinner-template",
    "template + progress spinner": "progress-spinner-template",
    "template más progress spinner": "progress-spinner-template",
    "template mas progress spinner": "progress-spinner-template",
    "templates en progress spinner": "progress-spinner-template",
    "templates con progress spinner": "progress-spinner-template",
    "templates de progress spinner": "progress-spinner-template",
    "templates + progress spinner": "progress-spinner-template",
    "templates más progress spinner": "progress-spinner-template",
    "templates mas progress spinner": "progress-spinner-template",
    # progress-spinner-theme
    "cargando y variables css": "progress-spinner-theme",
    "cargando + variables css": "progress-spinner-theme",
    "cargando mas variables css": "progress-spinner-theme",
    "cargando más variables css": "progress-spinner-theme",
    "variables css de la cargando": "progress-spinner-theme",
    "variables css y cargando": "progress-spinner-theme",
    "variables css + cargando": "progress-spinner-theme",
    "variables css mas cargando": "progress-spinner-theme",
    "variables css más cargando": "progress-spinner-theme",
    "variables css del componente cargando": "progress-spinner-theme",
    "variables css y componente cargando": "progress-spinner-theme",
    "variables css + componente cargando": "progress-spinner-theme",
    "variables css mas componente cargando": "progress-spinner-theme",
    "variables css más componente cargando": "progress-spinner-theme",
    "loading y variables css": "progress-spinner-theme",
    "loading + variables css": "progress-spinner-theme",
    "loading mas variables css": "progress-spinner-theme",
    "loading más variables css": "progress-spinner-theme",
    "variables css del loading": "progress-spinner-theme",
    "variables css y loading": "progress-spinner-theme",
    "variables css + loading": "progress-spinner-theme",
    "variables css mas loading": "progress-spinner-theme",
    "variables css más loading": "progress-spinner-theme",
    "variables css del componente loading": "progress-spinner-theme",
    "variables css y componente loading": "progress-spinner-theme",
    "variables css + componente loading": "progress-spinner-theme",
    "variables css mas componente loading": "progress-spinner-theme",
    "variables css más componente loading": "progress-spinner-theme",
    "loading css variables": "progress-spinner-theme",
    "loading component css variables": "progress-spinner-theme",
    "css variables loading component": "progress-spinner-theme",
    "progress spinner y variables css": "progress-spinner-theme",
    "progress-spinner y variables css": "progress-spinner-theme",
    "progress spinner + variables css": "progress-spinner-theme",
    "progress-spinner + variables css": "progress-spinner-theme",
    "progress spinner mas variables css": "progress-spinner-theme",
    "progress-spinner mas variables css": "progress-spinner-theme",
    "progress spinner más variables css": "progress-spinner-theme",
    "progress-spinner más variables css": "progress-spinner-theme",
    "variables css del progress spinner": "progress-spinner-theme",
    "variables css del progress-spinner": "progress-spinner-theme",
    "variables css y progress spinner": "progress-spinner-theme",
    "variables css y progress-spinner": "progress-spinner-theme",
    "variables css + progress spinner": "progress-spinner-theme",
    "variables css + progress-spinner": "progress-spinner-theme",
    "variables css mas progress spinner": "progress-spinner-theme",
    "variables css mas progress-spinner": "progress-spinner-theme",
    "variables css más progress spinner": "progress-spinner-theme",
    "variables css más progress-spinner": "progress-spinner-theme",
    "variables css del componente progress spinner": "progress-spinner-theme",
    "variables css del componente progress-spinner": "progress-spinner-theme",
    "variables css y componente progress spinner": "progress-spinner-theme",
    "variables css y componente progress-spinner": "progress-spinner-theme",
    "variables css + componente progress spinner": "progress-spinner-theme",
    "variables css + componente progress-spinner": "progress-spinner-theme",
    "variables css mas componente progress spinner": "progress-spinner-theme",
    "variables css mas componente progress-spinner": "progress-spinner-theme",
    "variables css más componente progress spinner": "progress-spinner-theme",
    "variables css más componente progress-spinner": "progress-spinner-theme",
    "progress spinner css variables": "progress-spinner-theme",
    "progress spinner component css variables": "progress-spinner-theme",
    "css variables progress spinner component": "progress-spinner-theme",
    "progress-spinner css variables": "progress-spinner-theme",
    "progress-spinner component css variables": "progress-spinner-theme",
    "css variables progress-spinner component": "progress-spinner-theme",
}