# agent: { description, prefixes }
component_mapping_progress_bar_agent = {
    "progress-bar-general": { # Nombre de Agente
        "description": "Consultas sobre componente progress-bar",
        "prefixes": ["progress-bar-interface", "progress-bar-definition", "progress-bar-usage"] # Nombre de archivos .md a consultar
    },
    "progress-bar-template": { # Nombre de Agente
        "description": "Consultas sobre componente progress-bar y sus templates",
        "prefixes": ["progress-bar-interface", "progress-bar-definition", "progress-bar-usage", "progress-bar-template"] # Nombre de archivos .md a consultar
    },
    "progress-bar-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente progress-bar",
        "prefixes": ["progress-bar-interface", "progress-bar-definition", "progress-bar-usage", "progress-bar-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_progress_bar_query = {
    # progress-bar-general
    "ilibtbprogressbar": "progress-bar-general",
    "libtbprogressbarmodule": "progress-bar-general",
    "lib-tb-progress-bar": "progress-bar-general",
    "barra de progreso": "progress-bar-general",
    "progress bar": "progress-bar-general",
    "progress-bar": "progress-bar-general",
    # progress-bar-template
    "barra de progreso con template": "progress-bar-template",
    "barra de progreso y template": "progress-bar-template",
    "barra de progreso + template": "progress-bar-template",
    "barra de progreso más template": "progress-bar-template",
    "barra de progreso mas template": "progress-bar-template",
    "barra de progreso con templates": "progress-bar-template",
    "barra de progreso y templates": "progress-bar-template",
    "barra de progreso + templates": "progress-bar-template",
    "barra de progreso más templates": "progress-bar-template",
    "barra de progreso mas templates": "progress-bar-template",
    "template y barra de progreso": "progress-bar-template",
    "template en barra de progreso": "progress-bar-template",
    "template con barra de progreso": "progress-bar-template",
    "template de barra de progreso": "progress-bar-template",
    "template de la barra de progreso": "progress-bar-template",
    "template + barra de progreso": "progress-bar-template",
    "template más barra de progreso": "progress-bar-template",
    "template mas barra de progreso": "progress-bar-template",
    "templates en barra de progreso": "progress-bar-template",
    "templates con barra de progreso": "progress-bar-template",
    "templates de la barra de progreso": "progress-bar-template",
    "templates + barra de progreso": "progress-bar-template",
    "templates más barra de progreso": "progress-bar-template",
    "templates mas barra de progreso": "progress-bar-template",
    "progress-bar con template": "progress-bar-template",
    "progress-bar y template": "progress-bar-template",
    "progress-bar + template": "progress-bar-template",
    "progress-bar más template": "progress-bar-template",
    "progress-bar mas template": "progress-bar-template",
    "progress-bar con templates": "progress-bar-template",
    "progress-bar y templates": "progress-bar-template",
    "progress-bar + templates": "progress-bar-template",
    "progress-bar más templates": "progress-bar-template",
    "progress-bar mas templates": "progress-bar-template",
    "template en progress-bar": "progress-bar-template",
    "template con progress-bar": "progress-bar-template",
    "template de progress-bar": "progress-bar-template",
    "template + progress-bar": "progress-bar-template",
    "template más progress-bar": "progress-bar-template",
    "template mas progress-bar": "progress-bar-template",
    "templates en progress-bar": "progress-bar-template",
    "templates con progress-bar": "progress-bar-template",
    "templates de progress-bar": "progress-bar-template",
    "templates + progress-bar": "progress-bar-template",
    "templates más progress-bar": "progress-bar-template",
    "templates mas progress-bar": "progress-bar-template",
    "progress bar con template": "progress-bar-template",
    "progress bar y template": "progress-bar-template",
    "progress bar + template": "progress-bar-template",
    "progress bar más template": "progress-bar-template",
    "progress bar mas template": "progress-bar-template",
    "progress bar con templates": "progress-bar-template",
    "progress bar y templates": "progress-bar-template",
    "progress bar + templates": "progress-bar-template",
    "progress bar más templates": "progress-bar-template",
    "progress bar mas templates": "progress-bar-template",
    "template en progress bar": "progress-bar-template",
    "template con progress bar": "progress-bar-template",
    "template de progress bar": "progress-bar-template",
    "template + progress bar": "progress-bar-template",
    "template más progress bar": "progress-bar-template",
    "template mas progress bar": "progress-bar-template",
    "templates en progress bar": "progress-bar-template",
    "templates con progress bar": "progress-bar-template",
    "templates de progress bar": "progress-bar-template",
    "templates + progress bar": "progress-bar-template",
    "templates más progress bar": "progress-bar-template",
    "templates mas progress bar": "progress-bar-template",
    # progress-bar-theme
    "barra de progreso y variables css": "progress-bar-theme",
    "barra de progreso + variables css": "progress-bar-theme",
    "barra de progreso mas variables css": "progress-bar-theme",
    "barra de progreso más variables css": "progress-bar-theme",
    "variables css de la barra de progreso": "progress-bar-theme",
    "variables css y barra de progreso": "progress-bar-theme",
    "variables css + barra de progreso": "progress-bar-theme",
    "variables css mas barra de progreso": "progress-bar-theme",
    "variables css más barra de progreso": "progress-bar-theme",
    "variables css del componente barra de progreso": "progress-bar-theme",
    "variables css y componente barra de progreso": "progress-bar-theme",
    "variables css + componente barra de progreso": "progress-bar-theme",
    "variables css mas componente barra de progreso": "progress-bar-theme",
    "variables css más componente barra de progreso": "progress-bar-theme",
    "progress bar y variables css": "progress-bar-theme",
    "progress-bar y variables css": "progress-bar-theme",
    "progress bar + variables css": "progress-bar-theme",
    "progress-bar + variables css": "progress-bar-theme",
    "progress bar mas variables css": "progress-bar-theme",
    "progress-bar mas variables css": "progress-bar-theme",
    "progress bar más variables css": "progress-bar-theme",
    "progress-bar más variables css": "progress-bar-theme",
    "variables css del progress bar": "progress-bar-theme",
    "variables css del progress-bar": "progress-bar-theme",
    "variables css y progress bar": "progress-bar-theme",
    "variables css y progress-bar": "progress-bar-theme",
    "variables css + progress bar": "progress-bar-theme",
    "variables css + progress-bar": "progress-bar-theme",
    "variables css mas progress bar": "progress-bar-theme",
    "variables css mas progress-bar": "progress-bar-theme",
    "variables css más progress bar": "progress-bar-theme",
    "variables css más progress-bar": "progress-bar-theme",
    "variables css del componente progress bar": "progress-bar-theme",
    "variables css del componente progress-bar": "progress-bar-theme",
    "variables css y componente progress bar": "progress-bar-theme",
    "variables css y componente progress-bar": "progress-bar-theme",
    "variables css + componente progress bar": "progress-bar-theme",
    "variables css + componente progress-bar": "progress-bar-theme",
    "variables css mas componente progress bar": "progress-bar-theme",
    "variables css mas componente progress-bar": "progress-bar-theme",
    "variables css más componente progress bar": "progress-bar-theme",
    "variables css más componente progress-bar": "progress-bar-theme",
    "progress bar css variables": "progress-bar-theme",
    "progress bar component css variables": "progress-bar-theme",
    "css variables progress bar component": "progress-bar-theme",
    "progress-bar css variables": "progress-bar-theme",
    "progress-bar component css variables": "progress-bar-theme",
    "css variables progress-bar component": "progress-bar-theme",
}