# agent: { description, prefixes }
component_mapping_answer_state_agent = {
    "answer-state-general": { # Nombre de Agente
        "description": "Consultas sobre componente answer-state",
        "prefixes": ["answer-state-interface", "answer-state-definition", "answer-state-usage"] # Nombre de archivos .md a consultar
    },
    "answer-state-template": { # Nombre de Agente
        "description": "Consultas sobre componente answer-state y sus templates",
        "prefixes": ["answer-state-interface", "answer-state-definition", "answer-state-usage", "answer-state-template"] # Nombre de archivos .md a consultar
    },
    "answer-state-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente answer-state",
        "prefixes": ["answer-state-interface", "answer-state-definition", "answer-state-usage", "answer-state-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_answer_state_query = {
    # answer-state-general
    "ilibtbanswerstate": "answer-state-general",
    "libtbanswerstatemodule": "answer-state-general",
    "lib-tb-answer-state": "answer-state-general",
    "answer state": "answer-state-general",
    "answer-state": "answer-state-general",
    # answer-state-template
    "answer-state con template": "answer-state-template",
    "answer-state y template": "answer-state-template",
    "answer-state + template": "answer-state-template",
    "answer-state más template": "answer-state-template",
    "answer-state mas template": "answer-state-template",
    "answer-state con templates": "answer-state-template",
    "answer-state y templates": "answer-state-template",
    "answer-state + templates": "answer-state-template",
    "answer-state más templates": "answer-state-template",
    "answer-state mas templates": "answer-state-template",
    "template en answer-state": "answer-state-template",
    "template con answer-state": "answer-state-template",
    "template de answer-state": "answer-state-template",
    "template + answer-state": "answer-state-template",
    "template más answer-state": "answer-state-template",
    "template mas answer-state": "answer-state-template",
    "templates en answer-state": "answer-state-template",
    "templates con answer-state": "answer-state-template",
    "templates de answer-state": "answer-state-template",
    "templates + answer-state": "answer-state-template",
    "templates más answer-state": "answer-state-template",
    "templates mas answer-state": "answer-state-template",
    "answer state con template": "answer-state-template",
    "answer state y template": "answer-state-template",
    "answer state + template": "answer-state-template",
    "answer state más template": "answer-state-template",
    "answer state mas template": "answer-state-template",
    "answer state con templates": "answer-state-template",
    "answer state y templates": "answer-state-template",
    "answer state + templates": "answer-state-template",
    "answer state más templates": "answer-state-template",
    "answer state mas templates": "answer-state-template",
    "template en answer state": "answer-state-template",
    "template con answer state": "answer-state-template",
    "template de answer state": "answer-state-template",
    "template del answer state": "answer-state-template",
    "template + answer state": "answer-state-template",
    "template más answer state": "answer-state-template",
    "template mas answer state": "answer-state-template",
    "templates en answer state": "answer-state-template",
    "templates con answer state": "answer-state-template",
    "templates de answer state": "answer-state-template",
    "templates del answer state": "answer-state-template",
    "templates + answer state": "answer-state-template",
    "templates más answer state": "answer-state-template",
    "templates mas answer state": "answer-state-template",
    # answer-state-theme
    "answer state y variables css": "answer-state-theme",
    "answer-state y variables css": "answer-state-theme",
    "answer state + variables css": "answer-state-theme",
    "answer-state + variables css": "answer-state-theme",
    "answer state mas variables css": "answer-state-theme",
    "answer-state mas variables css": "answer-state-theme",
    "answer state más variables css": "answer-state-theme",
    "answer-state más variables css": "answer-state-theme",
    "variables css del answer state": "answer-state-theme",
    "variables css del answer-state": "answer-state-theme",
    "variables css y answer state": "answer-state-theme",
    "variables css y answer-state": "answer-state-theme",
    "variables css + answer state": "answer-state-theme",
    "variables css + answer-state": "answer-state-theme",
    "variables css mas answer state": "answer-state-theme",
    "variables css mas answer-state": "answer-state-theme",
    "variables css más answer state": "answer-state-theme",
    "variables css más answer-state": "answer-state-theme",
    "variables css del componente answer state": "answer-state-theme",
    "variables css del componente answer-state": "answer-state-theme",
    "variables css y componente answer state": "answer-state-theme",
    "variables css y componente answer-state": "answer-state-theme",
    "variables css + componente answer state": "answer-state-theme",
    "variables css + componente answer-state": "answer-state-theme",
    "variables css mas componente answer state": "answer-state-theme",
    "variables css mas componente answer-state": "answer-state-theme",
    "variables css más componente answer state": "answer-state-theme",
    "variables css más componente answer-state": "answer-state-theme",
    "answer state css variables": "answer-state-theme",
    "answer state component css variables": "answer-state-theme",
    "css variables answer state component": "answer-state-theme",
    "answer-state css variables": "answer-state-theme",
    "answer-state component css variables": "answer-state-theme",
    "css variables answer-state component": "answer-state-theme",
}