# agent: { description, prefixes }
component_mapping_empty_state_agent = {
    "empty-state-general": { # Nombre de Agente
        "description": "Consultas sobre componente empty-state",
        "prefixes": ["empty-state-interface", "empty-state-definition", "empty-state-usage"] # Nombre de archivos .md a consultar
    },
    "empty-state-template": { # Nombre de Agente
        "description": "Consultas sobre componente empty-state y sus templates",
        "prefixes": ["empty-state-interface", "empty-state-definition", "empty-state-usage", "empty-state-template"] # Nombre de archivos .md a consultar
    },
    "empty-state-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente empty-state",
        "prefixes": ["empty-state-interface", "empty-state-definition", "empty-state-usage", "empty-state-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_empty_state_query = {
    # empty-state-general
    "ilibtbemptystate": "empty-state-general",
    "libtbemptystatemodule": "empty-state-general",
    "lib-tb-empty-state": "empty-state-general",
    "empty state": "empty-state-general",
    "empty-state": "empty-state-general",
    # empty-state-template
    "empty-state con template": "empty-state-template",
    "empty-state y template": "empty-state-template",
    "empty-state + template": "empty-state-template",
    "empty-state más template": "empty-state-template",
    "empty-state mas template": "empty-state-template",
    "empty-state con templates": "empty-state-template",
    "empty-state y templates": "empty-state-template",
    "empty-state + templates": "empty-state-template",
    "empty-state más templates": "empty-state-template",
    "empty-state mas templates": "empty-state-template",
    "template en empty-state": "empty-state-template",
    "template con empty-state": "empty-state-template",
    "template de empty-state": "empty-state-template",
    "template + empty-state": "empty-state-template",
    "template más empty-state": "empty-state-template",
    "template mas empty-state": "empty-state-template",
    "templates en empty-state": "empty-state-template",
    "templates con empty-state": "empty-state-template",
    "templates de empty-state": "empty-state-template",
    "templates + empty-state": "empty-state-template",
    "templates más empty-state": "empty-state-template",
    "templates mas empty-state": "empty-state-template",
    "empty state con template": "empty-state-template",
    "empty state y template": "empty-state-template",
    "empty state + template": "empty-state-template",
    "empty state más template": "empty-state-template",
    "empty state mas template": "empty-state-template",
    "empty state con templates": "empty-state-template",
    "empty state y templates": "empty-state-template",
    "empty state + templates": "empty-state-template",
    "empty state más templates": "empty-state-template",
    "empty state mas templates": "empty-state-template",
    "template en empty state": "empty-state-template",
    "template con empty state": "empty-state-template",
    "template de empty state": "empty-state-template",
    "template del empty state": "empty-state-template",
    "template + empty state": "empty-state-template",
    "template más empty state": "empty-state-template",
    "template mas empty state": "empty-state-template",
    "templates en empty state": "empty-state-template",
    "templates con empty state": "empty-state-template",
    "templates de empty state": "empty-state-template",
    "templates del empty state": "empty-state-template",
    "templates + empty state": "empty-state-template",
    "templates más empty state": "empty-state-template",
    "templates mas empty state": "empty-state-template",
    # empty-state-theme
    "empty state y variables css": "empty-state-theme",
    "empty-state y variables css": "empty-state-theme",
    "empty state + variables css": "empty-state-theme",
    "empty-state + variables css": "empty-state-theme",
    "empty state mas variables css": "empty-state-theme",
    "empty-state mas variables css": "empty-state-theme",
    "empty state más variables css": "empty-state-theme",
    "empty-state más variables css": "empty-state-theme",
    "variables css del empty state": "empty-state-theme",
    "variables css del empty-state": "empty-state-theme",
    "variables css y empty state": "empty-state-theme",
    "variables css y empty-state": "empty-state-theme",
    "variables css + empty state": "empty-state-theme",
    "variables css + empty-state": "empty-state-theme",
    "variables css mas empty state": "empty-state-theme",
    "variables css mas empty-state": "empty-state-theme",
    "variables css más empty state": "empty-state-theme",
    "variables css más empty-state": "empty-state-theme",
    "variables css del componente empty state": "empty-state-theme",
    "variables css del componente empty-state": "empty-state-theme",
    "variables css y componente empty state": "empty-state-theme",
    "variables css y componente empty-state": "empty-state-theme",
    "variables css + componente empty state": "empty-state-theme",
    "variables css + componente empty-state": "empty-state-theme",
    "variables css mas componente empty state": "empty-state-theme",
    "variables css mas componente empty-state": "empty-state-theme",
    "variables css más componente empty state": "empty-state-theme",
    "variables css más componente empty-state": "empty-state-theme",
    "empty state css variables": "empty-state-theme",
    "empty state component css variables": "empty-state-theme",
    "css variables empty state component": "empty-state-theme",
    "empty-state css variables": "empty-state-theme",
    "empty-state component css variables": "empty-state-theme",
    "css variables empty-state component": "empty-state-theme",
}