# agent: { description, prefixes }
component_mapping_carousel_agent = {
    "carousel-general": { # Nombre de Agente
        "description": "Consultas sobre componente carousel",
        "prefixes": ["carousel-interface", "carousel-definition", "carousel-usage"] # Nombre de archivos .md a consultar
    },
    "carousel-template": { # Nombre de Agente
        "description": "Consultas sobre componente carousel y sus templates",
        "prefixes": ["carousel-interface", "carousel-definition", "carousel-usage", "carousel-template"] # Nombre de archivos .md a consultar
    },
    "carousel-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente carousel",
        "prefixes": ["carousel-interface", "carousel-definition", "carousel-usage", "carousel-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_carousel_query = {
    # carousel-general
    "ilibtbcarousel": "carousel-general",
    "libtbcarouselmodule": "carousel-general",
    "lib-tb-carousel": "carousel-general",
    "carrusel": "carousel-general",
    "carousel": "carousel-general",
    # carousel-template
    "carrusel con template": "carousel-template",
    "carrusel y template": "carousel-template",
    "carrusel + template": "carousel-template",
    "carrusel más template": "carousel-template",
    "carrusel mas template": "carousel-template",
    "carrusel con templates": "carousel-template",
    "carrusel y templates": "carousel-template",
    "carrusel + templates": "carousel-template",
    "carrusel más templates": "carousel-template",
    "carrusel mas templates": "carousel-template",
    "template y carrusel": "carousel-template",
    "template en carrusel": "carousel-template",
    "template con carrusel": "carousel-template",
    "template de carrusel": "carousel-template",
    "template + carrusel": "carousel-template",
    "template más carrusel": "carousel-template",
    "template mas carrusel": "carousel-template",
    "templates y carrusel": "carousel-template",
    "templates en carrusel": "carousel-template",
    "templates con carrusel": "carousel-template",
    "templates de carrusel": "carousel-template",
    "templates + carrusel": "carousel-template",
    "templates más carrusel": "carousel-template",
    "templates mas carrusel": "carousel-template",
    "carousel con template": "carousel-template",
    "carousel y template": "carousel-template",
    "carousel + template": "carousel-template",
    "carousel más template": "carousel-template",
    "carousel mas template": "carousel-template",
    "carousel con templates": "carousel-template",
    "carousel y templates": "carousel-template",
    "carousel + templates": "carousel-template",
    "carousel más templates": "carousel-template",
    "carousel mas templates": "carousel-template",
    "template y carousel": "carousel-template",
    "template en carousel": "carousel-template",
    "template con carousel": "carousel-template",
    "template de carousel": "carousel-template",
    "template + carousel": "carousel-template",
    "template más carousel": "carousel-template",
    "template mas carousel": "carousel-template",
    "templates y carousel": "carousel-template",
    "templates en carousel": "carousel-template",
    "templates con carousel": "carousel-template",
    "templates de carousel": "carousel-template",
    "templates + carousel": "carousel-template",
    "templates más carousel": "carousel-template",
    "templates mas carousel": "carousel-template",
    # carousel-theme
    "carrusel y variables css": "carousel-theme",
    "carrusel y variables css": "carousel-theme",
    "carrusel + variables css": "carousel-theme",
    "carrusel + variables css": "carousel-theme",
    "carrusel mas variables css": "carousel-theme",
    "carrusel mas variables css": "carousel-theme",
    "carrusel más variables css": "carousel-theme",
    "carrusel más variables css": "carousel-theme",
    "variables css del carrusel": "carousel-theme",
    "variables css del carrusel": "carousel-theme",
    "variables css y carrusel": "carousel-theme",
    "variables css y carrusel": "carousel-theme",
    "variables css + carrusel": "carousel-theme",
    "variables css + carrusel": "carousel-theme",
    "variables css mas carrusel": "carousel-theme",
    "variables css mas carrusel": "carousel-theme",
    "variables css más carrusel": "carousel-theme",
    "variables css más carrusel": "carousel-theme",
    "variables css del componente carrusel": "carousel-theme",
    "variables css del componente carrusel": "carousel-theme",
    "variables css y componente carrusel": "carousel-theme",
    "variables css y componente carrusel": "carousel-theme",
    "variables css + componente carrusel": "carousel-theme",
    "variables css + componente carrusel": "carousel-theme",
    "variables css mas componente carrusel": "carousel-theme",
    "variables css mas componente carrusel": "carousel-theme",
    "variables css más componente carrusel": "carousel-theme",
    "variables css más componente carrusel": "carousel-theme",
    "carousel y variables css": "carousel-theme",
    "carousel y variables css": "carousel-theme",
    "carousel + variables css": "carousel-theme",
    "carousel + variables css": "carousel-theme",
    "carousel mas variables css": "carousel-theme",
    "carousel mas variables css": "carousel-theme",
    "carousel más variables css": "carousel-theme",
    "carousel más variables css": "carousel-theme",
    "variables css del carousel": "carousel-theme",
    "variables css del carousel": "carousel-theme",
    "variables css y carousel": "carousel-theme",
    "variables css y carousel": "carousel-theme",
    "variables css + carousel": "carousel-theme",
    "variables css + carousel": "carousel-theme",
    "variables css mas carousel": "carousel-theme",
    "variables css mas carousel": "carousel-theme",
    "variables css más carousel": "carousel-theme",
    "variables css más carousel": "carousel-theme",
    "variables css del componente carousel": "carousel-theme",
    "variables css del componente carousel": "carousel-theme",
    "variables css y componente carousel": "carousel-theme",
    "variables css y componente carousel": "carousel-theme",
    "variables css + componente carousel": "carousel-theme",
    "variables css + componente carousel": "carousel-theme",
    "variables css mas componente carousel": "carousel-theme",
    "variables css mas componente carousel": "carousel-theme",
    "variables css más componente carousel": "carousel-theme",
    "variables css más componente carousel": "carousel-theme",
    "carousel css variables": "carousel-theme",
    "carousel component css variables": "carousel-theme",
    "css variables carousel component": "carousel-theme",
}