# agent: { description, prefixes }
component_mapping_alert_agent = {
    "alert-general": { # Nombre de Agente
        "description": "Consultas sobre componente alert",
        "prefixes": ["alert-interface", "alert-definition", "alert-usage"] # Nombre de archivos .md a consultar
    },
    "alert-template": { # Nombre de Agente
        "description": "Consultas sobre componente alert y sus templates",
        "prefixes": ["alert-interface", "alert-definition", "alert-usage", "alert-template"] # Nombre de archivos .md a consultar
    },
    "alert-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente alert",
        "prefixes": ["alert-interface", "alert-definition", "alert-usage", "alert-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_alert_query = {
    # alert-general
    "ilibtbalert": "alert-general",
    "ilibtbalertmessage": "alert-general",
    "libtbalertmodule": "alert-general",
    "lib-tb-alert": "alert-general",
    "alerta": "alert-general",
    "alert": "alert-general",
    # alert-template
    "alerta con template": "alert-template",
    "alerta y template": "alert-template",
    "alerta + template": "alert-template",
    "alerta más template": "alert-template",
    "alerta mas template": "alert-template",
    "alerta con templates": "alert-template",
    "alerta y templates": "alert-template",
    "alerta + templates": "alert-template",
    "alerta más templates": "alert-template",
    "alerta mas templates": "alert-template",
    "template y alerta": "alert-template",
    "template en alerta": "alert-template",
    "template con alerta": "alert-template",
    "template de alerta": "alert-template",
    "template + alerta": "alert-template",
    "template más alerta": "alert-template",
    "template mas alerta": "alert-template",
    "templates en alerta": "alert-template",
    "templates con alerta": "alert-template",
    "templates de alerta": "alert-template",
    "templates + alerta": "alert-template",
    "templates más alerta": "alert-template",
    "templates mas alerta": "alert-template",
    "alert con template": "alert-template",
    "alert y template": "alert-template",
    "alert + template": "alert-template",
    "alert más template": "alert-template",
    "alert mas template": "alert-template",
    "alert con templates": "alert-template",
    "alert y templates": "alert-template",
    "alert + templates": "alert-template",
    "alert más templates": "alert-template",
    "alert mas templates": "alert-template",
    "template en alert": "alert-template",
    "template con alert": "alert-template",
    "template de alert": "alert-template",
    "template + alert": "alert-template",
    "template más alert": "alert-template",
    "template mas alert": "alert-template",
    "templates en alert": "alert-template",
    "templates con alert": "alert-template",
    "templates de alert": "alert-template",
    "templates + alert": "alert-template",
    "templates más alert": "alert-template",
    "templates mas alert": "alert-template",
    # alert-theme
    "alerta y variables css": "alert-theme",
    "alerta y variables css": "alert-theme",
    "alerta + variables css": "alert-theme",
    "alerta + variables css": "alert-theme",
    "alerta mas variables css": "alert-theme",
    "alerta mas variables css": "alert-theme",
    "alerta más variables css": "alert-theme",
    "alerta más variables css": "alert-theme",
    "variables css de la alerta": "alert-theme",
    "variables css de la alerta": "alert-theme",
    "variables css y alerta": "alert-theme",
    "variables css y alerta": "alert-theme",
    "variables css + alerta": "alert-theme",
    "variables css + alerta": "alert-theme",
    "variables css mas alerta": "alert-theme",
    "variables css mas alerta": "alert-theme",
    "variables css más alerta": "alert-theme",
    "variables css más alerta": "alert-theme",
    "variables css del componente alerta": "alert-theme",
    "variables css del componente alerta": "alert-theme",
    "variables css y componente alerta": "alert-theme",
    "variables css y componente alerta": "alert-theme",
    "variables css + componente alerta": "alert-theme",
    "variables css + componente alerta": "alert-theme",
    "variables css mas componente alerta": "alert-theme",
    "variables css mas componente alerta": "alert-theme",
    "variables css más componente alerta": "alert-theme",
    "variables css más componente alerta": "alert-theme",
    "alert y variables css": "alert-theme",
    "alert y variables css": "alert-theme",
    "alert + variables css": "alert-theme",
    "alert + variables css": "alert-theme",
    "alert mas variables css": "alert-theme",
    "alert mas variables css": "alert-theme",
    "alert más variables css": "alert-theme",
    "alert más variables css": "alert-theme",
    "variables css del alert": "alert-theme",
    "variables css del alert": "alert-theme",
    "variables css y alert": "alert-theme",
    "variables css y alert": "alert-theme",
    "variables css + alert": "alert-theme",
    "variables css + alert": "alert-theme",
    "variables css mas alert": "alert-theme",
    "variables css mas alert": "alert-theme",
    "variables css más alert": "alert-theme",
    "variables css más alert": "alert-theme",
    "variables css del componente alert": "alert-theme",
    "variables css del componente alert": "alert-theme",
    "variables css y componente alert": "alert-theme",
    "variables css y componente alert": "alert-theme",
    "variables css + componente alert": "alert-theme",
    "variables css + componente alert": "alert-theme",
    "variables css mas componente alert": "alert-theme",
    "variables css mas componente alert": "alert-theme",
    "variables css más componente alert": "alert-theme",
    "variables css más componente alert": "alert-theme",
    "alert css variables": "alert-theme",
    "alert component css variables": "alert-theme",
    "css variables alert component": "alert-theme",
    "alert css variables": "alert-theme",
    "alert component css variables": "alert-theme",
    "css variables alert component": "alert-theme",
}