# agent: { description, prefixes }
component_mapping_input_number_agent = {
    "input-number-general": { # Nombre de Agente
        "description": "Consultas sobre componente input-number",
        "prefixes": ["input-number-interface", "input-number-definition", "input-number-usage"] # Nombre de archivos .md a consultar
    },
    "input-number-template": { # Nombre de Agente
        "description": "Consultas sobre componente input-number y sus templates",
        "prefixes": ["input-number-interface", "input-number-definition", "input-number-usage", "input-number-template"] # Nombre de archivos .md a consultar
    },
    "input-number-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente input-number",
        "prefixes": ["input-number-interface", "input-number-definition", "input-number-usage", "input-number-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_input_number_query = {
    # input-number-general
    "ilibtbinputnumber": "input-number-general",
    "libtbinputnumbermodule": "input-number-general",
    "lib-tb-input-number": "input-number-general",
    "entrada de texto de números": "input-number-general",
    "entrada de texto de numeros": "input-number-general",
    "entrada de números": "input-number-general",
    "entrada de numeros": "input-number-general",
    "entrada de texto numérico": "input-number-general",
    "entrada de texto numerico": "input-number-general",
    "entrada de texto numérica": "input-number-general",
    "entrada de texto numerica": "input-number-general",
    "entrada numérica": "input-number-general",
    "entrada numerica": "input-number-general",
    "entrada de texto de solo números": "input-number-general",
    "entrada de texto de solo numeros": "input-number-general",
    "campo de texto de números": "input-number-general",
    "campo de texto de numeros": "input-number-general",
    "campo de números": "input-number-general",
    "campo de numeros": "input-number-general",
    "campo de texto numérico": "input-number-general",
    "campo de texto numerico": "input-number-general",
    "campo numérico": "input-number-general",
    "campo numerico": "input-number-general",
    "campo de texto de solo números": "input-number-general",
    "campo de texto de solo numeros": "input-number-general",
    "input de números": "input-number-general",
    "input de numeros": "input-number-general",
    "inputs de números": "input-number-general",
    "inputs de numeros": "input-number-general",
    "input numérico": "input-number-general",
    "inputs numéricos": "input-number-general",
    "input numerico": "input-number-general",
    "inputs numericos": "input-number-general",
    "input number": "input-number-general",
    "input-number": "input-number-general",
    # input-number-template
    "input-number con template": "input-number-template",
    "input-number y template": "input-number-template",
    "input-number + template": "input-number-template",
    "input-number más template": "input-number-template",
    "input-number mas template": "input-number-template",
    "input-number con templates": "input-number-template",
    "input-number y templates": "input-number-template",
    "input-number + templates": "input-number-template",
    "input-number más templates": "input-number-template",
    "input-number mas templates": "input-number-template",
    "template en input-number": "input-number-template",
    "template con input-number": "input-number-template",
    "template de input-number": "input-number-template",
    "template + input-number": "input-number-template",
    "template más input-number": "input-number-template",
    "template mas input-number": "input-number-template",
    "templates en input-number": "input-number-template",
    "templates con input-number": "input-number-template",
    "templates de input-number": "input-number-template",
    "templates + input-number": "input-number-template",
    "templates más input-number": "input-number-template",
    "templates mas input-number": "input-number-template",
    "input number con template": "input-number-template",
    "input number y template": "input-number-template",
    "input number + template": "input-number-template",
    "input number más template": "input-number-template",
    "input number mas template": "input-number-template",
    "input number con templates": "input-number-template",
    "input number y templates": "input-number-template",
    "input number + templates": "input-number-template",
    "input number más templates": "input-number-template",
    "input number mas templates": "input-number-template",
    "template en input number": "input-number-template",
    "template con input number": "input-number-template",
    "template de input number": "input-number-template",
    "template + input number": "input-number-template",
    "template más input number": "input-number-template",
    "template mas input number": "input-number-template",
    "templates en input number": "input-number-template",
    "templates con input number": "input-number-template",
    "templates de input number": "input-number-template",
    "templates + input number": "input-number-template",
    "templates más input number": "input-number-template",
    "templates mas input number": "input-number-template",
    # input-number-theme
    "input de números y variables css": "input-number-theme",
    "input de numeros y variables css": "input-number-theme",
    "inputs de números y variables css": "input-number-theme",
    "inputs de numeros y variables css": "input-number-theme",
    "input numérico y variables css": "input-number-theme",
    "input numerico y variables css": "input-number-theme",
    "inputs numéricos y variables css": "input-number-theme",
    "inputs numericos y variables css": "input-number-theme",
    "input number y variables css": "input-number-theme",
    "input-number y variables css": "input-number-theme",
    "input de números + variables css": "input-number-theme",
    "input de numeros + variables css": "input-number-theme",
    "inputs de números + variables css": "input-number-theme",
    "inputs de numeros + variables css": "input-number-theme",
    "input numérico + variables css": "input-number-theme",
    "input numerico + variables css": "input-number-theme",
    "inputs numéricos + variables css": "input-number-theme",
    "inputs numericos + variables css": "input-number-theme",
    "input number + variables css": "input-number-theme",
    "input-number + variables css": "input-number-theme",
    "input de números mas variables css": "input-number-theme",
    "input de numeros mas variables css": "input-number-theme",
    "inputs de números mas variables css": "input-number-theme",
    "inputs de numeros mas variables css": "input-number-theme",
    "input numérico mas variables css": "input-number-theme",
    "input numerico mas variables css": "input-number-theme",
    "inputs numéricos mas variables css": "input-number-theme",
    "inputs numericos mas variables css": "input-number-theme",
    "input number mas variables css": "input-number-theme",
    "input-number mas variables css": "input-number-theme",
    "input de números más variables css": "input-number-theme",
    "input de numeros más variables css": "input-number-theme",
    "inputs de números más variables css": "input-number-theme",
    "inputs de numeros más variables css": "input-number-theme",
    "input numérico más variables css": "input-number-theme",
    "input numerico más variables css": "input-number-theme",
    "inputs numéricos más variables css": "input-number-theme",
    "inputs numericos más variables css": "input-number-theme",
    "input number más variables css": "input-number-theme",
    "input-number más variables css": "input-number-theme",
    "variables css del input de números": "input-number-theme",
    "variables css del input de numeros": "input-number-theme",
    "variables css de inputs de números": "input-number-theme",
    "variables css de inputs de numeros": "input-number-theme",
    "variables css del input numérico": "input-number-theme",
    "variables css del input numerico": "input-number-theme",
    "variables css de inputs numéricos": "input-number-theme",
    "variables css de inputs numericos": "input-number-theme",
    "variables css del input number": "input-number-theme",
    "variables css del input-number": "input-number-theme",
    "variables css y input de números": "input-number-theme",
    "variables css y input de numeros": "input-number-theme",
    "variables css y inputs de números": "input-number-theme",
    "variables css y inputs de numeros": "input-number-theme",
    "variables css y input numérico": "input-number-theme",
    "variables css y input numerico": "input-number-theme",
    "variables css y inputs numéricos": "input-number-theme",
    "variables css y inputs numericos": "input-number-theme",
    "variables css y input number": "input-number-theme",
    "variables css y input-number": "input-number-theme",
    "variables css + input de números": "input-number-theme",
    "variables css + input de numeros": "input-number-theme",
    "variables css + inputs de números": "input-number-theme",
    "variables css + inputs de numeros": "input-number-theme",
    "variables css + input numérico": "input-number-theme",
    "variables css + input numerico": "input-number-theme",
    "variables css + inputs numéricos": "input-number-theme",
    "variables css + inputs numericos": "input-number-theme",
    "variables css + input number": "input-number-theme",
    "variables css + input-number": "input-number-theme",
    "variables css mas input de números": "input-number-theme",
    "variables css mas input de numeros": "input-number-theme",
    "variables css mas inputs de números": "input-number-theme",
    "variables css mas inputs de numeros": "input-number-theme",
    "variables css mas input numérico": "input-number-theme",
    "variables css mas input numerico": "input-number-theme",
    "variables css mas inputs numéricos": "input-number-theme",
    "variables css mas inputs numericos": "input-number-theme",
    "variables css mas input number": "input-number-theme",
    "variables css mas input-number": "input-number-theme",
    "variables css más input number": "input-number-theme",
    "variables css más input-number": "input-number-theme",
    "variables css del componente input de números": "input-number-theme",
    "variables css del componente input de numeros": "input-number-theme",
    "variables css del componente inputs de números": "input-number-theme",
    "variables css del componente inputs de numeros": "input-number-theme",
    "variables css del componente input numérico": "input-number-theme",
    "variables css del componente input numerico": "input-number-theme",
    "variables css del componente inputs numéricos": "input-number-theme",
    "variables css del componente inputs numericos": "input-number-theme",
    "variables css del componente input number": "input-number-theme",
    "variables css del componente input-number": "input-number-theme",
    "variables css y componente input de números": "input-number-theme",
    "variables css y componente input de numeros": "input-number-theme",
    "variables css y componente inputs de números": "input-number-theme",
    "variables css y componente inputs de numeros": "input-number-theme",
    "variables css y componente input numérico": "input-number-theme",
    "variables css y componente input numerico": "input-number-theme",
    "variables css y componente inputs numéricos": "input-number-theme",
    "variables css y componente inputs numericos": "input-number-theme",
    "variables css y componente input number": "input-number-theme",
    "variables css y componente input-number": "input-number-theme",
    "variables css + componente input de números": "input-number-theme",
    "variables css + componente input de numeros": "input-number-theme",
    "variables css + componente inputs de números": "input-number-theme",
    "variables css + componente inputs de numeros": "input-number-theme",
    "variables css + componente input numérico": "input-number-theme",
    "variables css + componente input numerico": "input-number-theme",
    "variables css + componente inputs numéricos": "input-number-theme",
    "variables css + componente inputs numericos": "input-number-theme",
    "variables css + componente input number": "input-number-theme",
    "variables css + componente input-number": "input-number-theme",
    "variables css mas componente input de números": "input-number-theme",
    "variables css mas componente input de numeros": "input-number-theme",
    "variables css mas componente inputs de números": "input-number-theme",
    "variables css mas componente inputs de numeros": "input-number-theme",
    "variables css mas componente input numérico": "input-number-theme",
    "variables css mas componente input numerico": "input-number-theme",
    "variables css mas componente inputs numéricos": "input-number-theme",
    "variables css mas componente inputs numericos": "input-number-theme",
    "variables css mas componente input number": "input-number-theme",
    "variables css mas componente input-number": "input-number-theme",
    "variables css más componente input de números": "input-number-theme",
    "variables css más componente input de numeros": "input-number-theme",
    "variables css más componente inputs de números": "input-number-theme",
    "variables css más componente inputs de numeros": "input-number-theme",
    "variables css más componente input numérico": "input-number-theme",
    "variables css más componente input numerico": "input-number-theme",
    "variables css más componente inputs numéricos": "input-number-theme",
    "variables css más componente inputs numericos": "input-number-theme",
    "variables css más componente input number": "input-number-theme",
    "variables css más componente input-number": "input-number-theme",
    "input number css variables": "input-number-theme",
    "input number component css variables": "input-number-theme",
    "css variables input number component": "input-number-theme",
    "input-number css variables": "input-number-theme",
    "input-number component css variables": "input-number-theme",
    "css variables input-number component": "input-number-theme",
}