# agent: { description, prefixes }
component_mapping_dropdown_multi_select_agent = {
    "dropdown-multi-select-general": { # Nombre de Agente
        "description": "Consultas sobre componente dropdown-multi-select",
        "prefixes": ["dropdown-multi-select-interface", "dropdown-multi-select-definition", "dropdown-multi-select-usage"] # Nombre de archivos .md a consultar
    },
    "dropdown-multi-select-template": { # Nombre de Agente
        "description": "Consultas sobre componente dropdown-multi-select y sus templates",
        "prefixes": ["dropdown-multi-select-interface", "dropdown-multi-select-definition", "dropdown-multi-select-usage", "dropdown-multi-select-template"] # Nombre de archivos .md a consultar
    },
    "dropdown-multi-select-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente dropdown-multi-select",
        "prefixes": ["dropdown-multi-select-interface", "dropdown-multi-select-definition","dropdown-multi-select-usage", "dropdown-multi-select-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_dropdown_multi_select_query = {
    # dropdown-multi-select-general
    "ilibtbdropdownmultiselect": "dropdown-multi-select-general",
    "libtbdropdownmultiselectmodule": "dropdown-multi-select-general",
    "lib-tb-dropdown-multi-select": "dropdown-multi-select-general",
    "dropdown multi select": "dropdown-multi-select-general",
    "dropdown-multi-select": "dropdown-multi-select-general",
    # dropdown-multi-select-template
    "dropdown multi select con template": "dropdown-multi-select-template",
    "dropdown multi select y template": "dropdown-multi-select-template",
    "dropdown multi select + template": "dropdown-multi-select-template",
    "dropdown multi select más template": "dropdown-multi-select-template",
    "dropdown multi select mas template": "dropdown-multi-select-template",
    "dropdown multi select con templates": "dropdown-multi-select-template",
    "dropdown multi select y templates": "dropdown-multi-select-template",
    "dropdown multi select + templates": "dropdown-multi-select-template",
    "dropdown multi select más templates": "dropdown-multi-select-template",
    "dropdown multi select mas templates": "dropdown-multi-select-template",
    "template en dropdown multi select": "dropdown-multi-select-template",
    "template con dropdown multi select": "dropdown-multi-select-template",
    "template de dropdown multi select": "dropdown-multi-select-template",
    "template + dropdown multi select": "dropdown-multi-select-template",
    "template más dropdown multi select": "dropdown-multi-select-template",
    "template mas dropdown multi select": "dropdown-multi-select-template",
    "templates en dropdown multi select": "dropdown-multi-select-template",
    "templates con dropdown multi select": "dropdown-multi-select-template",
    "templates de dropdown multi select": "dropdown-multi-select-template",
    "templates + dropdown multi select": "dropdown-multi-select-template",
    "templates más dropdown multi select": "dropdown-multi-select-template",
    "templates mas dropdown multi select": "dropdown-multi-select-template",
    "dropdown-multi-select con template": "dropdown-multi-select-template",
    "dropdown-multi-select y template": "dropdown-multi-select-template",
    "dropdown-multi-select + template": "dropdown-multi-select-template",
    "dropdown-multi-select más template": "dropdown-multi-select-template",
    "dropdown-multi-select mas template": "dropdown-multi-select-template",
    "dropdown-multi-select con templates": "dropdown-multi-select-template",
    "dropdown-multi-select y templates": "dropdown-multi-select-template",
    "dropdown-multi-select + templates": "dropdown-multi-select-template",
    "dropdown-multi-select más templates": "dropdown-multi-select-template",
    "dropdown-multi-select mas templates": "dropdown-multi-select-template",
    "template en dropdown-multi-select": "dropdown-multi-select-template",
    "template con dropdown-multi-select": "dropdown-multi-select-template",
    "template de dropdown-multi-select": "dropdown-multi-select-template",
    "template + dropdown-multi-select": "dropdown-multi-select-template",
    "template más dropdown-multi-select": "dropdown-multi-select-template",
    "template mas dropdown-multi-select": "dropdown-multi-select-template",
    "templates en dropdown-multi-select": "dropdown-multi-select-template",
    "templates con dropdown-multi-select": "dropdown-multi-select-template",
    "templates de dropdown-multi-select": "dropdown-multi-select-template",
    "templates + dropdown-multi-select": "dropdown-multi-select-template",
    "templates más dropdown-multi-select": "dropdown-multi-select-template",
    "templates mas dropdown-multi-select": "dropdown-multi-select-template",
    # dropdown-multi-select-theme
    "dropdown multi select y variables css": "dropdown-multi-select-theme",
    "dropdown-multi-select y variables css": "dropdown-multi-select-theme",
    "dropdown multi select + variables css": "dropdown-multi-select-theme",
    "dropdown-multi-select + variables css": "dropdown-multi-select-theme",
    "dropdown multi select mas variables css": "dropdown-multi-select-theme",
    "dropdown-multi-select mas variables css": "dropdown-multi-select-theme",
    "dropdown multi select más variables css": "dropdown-multi-select-theme",
    "dropdown-multi-select más variables css": "dropdown-multi-select-theme",
    "variables css del dropdown multi select": "dropdown-multi-select-theme",
    "variables css del dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css y dropdown multi select": "dropdown-multi-select-theme",
    "variables css y dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css + dropdown multi select": "dropdown-multi-select-theme",
    "variables css + dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css mas dropdown multi select": "dropdown-multi-select-theme",
    "variables css mas dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css más dropdown multi select": "dropdown-multi-select-theme",
    "variables css más dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css del componente dropdown multi select": "dropdown-multi-select-theme",
    "variables css del componente dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css y componente dropdown multi select": "dropdown-multi-select-theme",
    "variables css y componente dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css + componente dropdown multi select": "dropdown-multi-select-theme",
    "variables css + componente dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css mas componente dropdown multi select": "dropdown-multi-select-theme",
    "variables css mas componente dropdown-multi-select": "dropdown-multi-select-theme",
    "variables css más componente dropdown multi select": "dropdown-multi-select-theme",
    "variables css más componente dropdown-multi-select": "dropdown-multi-select-theme",
    "dropdown multi select css variables": "dropdown-multi-select-theme",
    "dropdown multi select component css variables": "dropdown-multi-select-theme",
    "css variables dropdown multi select component": "dropdown-multi-select-theme",
    "dropdown-multi-select css variables": "dropdown-multi-select-theme",
    "dropdown-multi-select component css variables": "dropdown-multi-select-theme",
    "css variables dropdown-multi-select component": "dropdown-multi-select-theme",
}