# agent: { description, prefixes }
component_mapping_table_agent = {
    "table-general": { # Nombre de Agente
        "description": "Consultas sobre componente table",
        "prefixes": ["table-interface", "table-definition", "table-usage"] # Nombre de archivos .md a consultar
    },
    "table-template": { # Nombre de Agente
        "description": "Consultas sobre componente table y sus templates",
        "prefixes": ["table-interface", "table-definition", "table-usage", "table-template"] # Nombre de archivos .md a consultar
    },
    "table-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente table",
        "prefixes": ["table-interface", "table-definition", "table-usage", "table-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_table_query = {
    # table-general
    "ilibtbtable": "table-general",
    "libtbtablemodule": "table-general",
    "lib-tb-table": "table-general",
    "tabla": "table-general",
    "table": "table-general",
    # table-template
    "tabla con template": "table-template",
    "tabla y template": "table-template",
    "tabla + template": "table-template",
    "tabla más template": "table-template",
    "tabla mas template": "table-template",
    "tabla con templates": "table-template",
    "tabla y templates": "table-template",
    "tabla + templates": "table-template",
    "tabla más templates": "table-template",
    "tabla mas templates": "table-template",
    "template y tabla": "table-template",
    "template en tabla": "table-template",
    "template con tabla": "table-template",
    "template de tabla": "table-template",
    "template de la tabla": "table-template",
    "template + tabla": "table-template",
    "template más tabla": "table-template",
    "template mas tabla": "table-template",
    "templates en tabla": "table-template",
    "templates con tabla": "table-template",
    "templates de tabla": "table-template",
    "templates de la tabla": "table-template",
    "templates + tabla": "table-template",
    "templates más tabla": "table-template",
    "templates mas tabla": "table-template",
    "table con template": "table-template",
    "table y template": "table-template",
    "table + template": "table-template",
    "table más template": "table-template",
    "table mas template": "table-template",
    "table con templates": "table-template",
    "table y templates": "table-template",
    "table + templates": "table-template",
    "table más templates": "table-template",
    "table mas templates": "table-template",
    "template en table": "table-template",
    "template con table": "table-template",
    "template de table": "table-template",
    "template + table": "table-template",
    "template más table": "table-template",
    "template mas table": "table-template",
    "templates en table": "table-template",
    "templates con table": "table-template",
    "templates de table": "table-template",
    "templates + table": "table-template",
    "templates más table": "table-template",
    "templates mas table": "table-template",
    # table-theme
    "tabla y variables css": "table-theme",
    "tabla + variables css": "table-theme",
    "tabla mas variables css": "table-theme",
    "tabla más variables css": "table-theme",
    "variables css de tabla": "table-theme",
    "variables css de la tabla": "table-theme",
    "variables css y tabla": "table-theme",
    "variables css + tabla": "table-theme",
    "variables css mas tabla": "table-theme",
    "variables css más tabla": "table-theme",
    "variables css del componente tabla": "table-theme",
    "variables css y componente tabla": "table-theme",
    "variables css + componente tabla": "table-theme",
    "variables css mas componente tabla": "table-theme",
    "variables css más componente tabla": "table-theme",
    "table y variables css": "table-theme",
    "table + variables css": "table-theme",
    "table mas variables css": "table-theme",
    "table más variables css": "table-theme",
    "variables css de table": "table-theme",
    "variables css del table": "table-theme",
    "variables css y table": "table-theme",
    "variables css + table": "table-theme",
    "variables css mas table": "table-theme",
    "variables css más table": "table-theme",
    "variables css del componente table": "table-theme",
    "variables css y componente table": "table-theme",
    "variables css + componente table": "table-theme",
    "variables css mas componente table": "table-theme",
    "variables css más componente table": "table-theme",
    "table css variables": "table-theme",
    "table component css variables": "table-theme",
    "css variables table component": "table-theme",
}