# agent: { description, prefixes }
component_mapping_paginator_agent = {
    "paginator-general": { # Nombre de Agente
        "description": "Consultas sobre componente paginator",
        "prefixes": ["paginator-interface", "paginator-definition", "paginator-usage"] # Nombre de archivos .md a consultar
    },
    "paginator-template": { # Nombre de Agente
        "description": "Consultas sobre componente paginator y sus templates",
        "prefixes": ["paginator-interface", "paginator-definition", "paginator-usage", "paginator-template"] # Nombre de archivos .md a consultar
    },
    "paginator-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente paginator",
        "prefixes": ["paginator-interface", "paginator-definition", "paginator-usage", "paginator-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_paginator_query = {
    # paginator-general
    "ilibtbpaginator": "paginator-general",
    "libtbpaginatormodule": "paginator-general",
    "lib-tb-paginator": "paginator-general",
    "paginador": "paginator-general",
    "paginator": "paginator-general",
    # paginator-template
    "paginador con template": "paginator-template",
    "paginador y template": "paginator-template",
    "paginador + template": "paginator-template",
    "paginador más template": "paginator-template",
    "paginador mas template": "paginator-template",
    "paginador con templates": "paginator-template",
    "paginador y templates": "paginator-template",
    "paginador + templates": "paginator-template",
    "paginador más templates": "paginator-template",
    "paginador mas templates": "paginator-template",
    "template y paginador": "paginator-template",
    "template en paginador": "paginator-template",
    "template con paginador": "paginator-template",
    "template de paginador": "paginator-template",
    "template + paginador": "paginator-template",
    "template más paginador": "paginator-template",
    "template mas paginador": "paginator-template",
    "templates en paginador": "paginator-template",
    "templates con paginador": "paginator-template",
    "templates de paginador": "paginator-template",
    "templates + paginador": "paginator-template",
    "templates más paginador": "paginator-template",
    "templates mas paginador": "paginator-template",
    "paginator con template": "paginator-template",
    "paginator y template": "paginator-template",
    "paginator + template": "paginator-template",
    "paginator más template": "paginator-template",
    "paginator mas template": "paginator-template",
    "paginator con templates": "paginator-template",
    "paginator y templates": "paginator-template",
    "paginator + templates": "paginator-template",
    "paginator más templates": "paginator-template",
    "paginator mas templates": "paginator-template",
    "template en paginator": "paginator-template",
    "template con paginator": "paginator-template",
    "template de paginator": "paginator-template",
    "template + paginator": "paginator-template",
    "template más paginator": "paginator-template",
    "template mas paginator": "paginator-template",
    "templates en paginator": "paginator-template",
    "templates con paginator": "paginator-template",
    "templates de paginator": "paginator-template",
    "templates + paginator": "paginator-template",
    "templates más paginator": "paginator-template",
    "templates mas paginator": "paginator-template",
    # paginator-theme
    "paginador y variables css": "paginator-theme",
    "paginador y variables css": "paginator-theme",
    "paginador + variables css": "paginator-theme",
    "paginador + variables css": "paginator-theme",
    "paginador mas variables css": "paginator-theme",
    "paginador mas variables css": "paginator-theme",
    "paginador más variables css": "paginator-theme",
    "paginador más variables css": "paginator-theme",
    "variables css del paginador": "paginator-theme",
    "variables css del paginador": "paginator-theme",
    "variables css y paginador": "paginator-theme",
    "variables css y paginador": "paginator-theme",
    "variables css + paginador": "paginator-theme",
    "variables css + paginador": "paginator-theme",
    "variables css mas paginador": "paginator-theme",
    "variables css mas paginador": "paginator-theme",
    "variables css más paginador": "paginator-theme",
    "variables css más paginador": "paginator-theme",
    "variables css del componente paginador": "paginator-theme",
    "variables css del componente paginador": "paginator-theme",
    "variables css y componente paginador": "paginator-theme",
    "variables css y componente paginador": "paginator-theme",
    "variables css + componente paginador": "paginator-theme",
    "variables css + componente paginador": "paginator-theme",
    "variables css mas componente paginador": "paginator-theme",
    "variables css mas componente paginador": "paginator-theme",
    "variables css más componente paginador": "paginator-theme",
    "variables css más componente paginador": "paginator-theme",
    "paginator y variables css": "paginator-theme",
    "paginator y variables css": "paginator-theme",
    "paginator + variables css": "paginator-theme",
    "paginator + variables css": "paginator-theme",
    "paginator mas variables css": "paginator-theme",
    "paginator mas variables css": "paginator-theme",
    "paginator más variables css": "paginator-theme",
    "paginator más variables css": "paginator-theme",
    "variables css del paginator": "paginator-theme",
    "variables css del paginator": "paginator-theme",
    "variables css y paginator": "paginator-theme",
    "variables css y paginator": "paginator-theme",
    "variables css + paginator": "paginator-theme",
    "variables css + paginator": "paginator-theme",
    "variables css mas paginator": "paginator-theme",
    "variables css mas paginator": "paginator-theme",
    "variables css más paginator": "paginator-theme",
    "variables css más paginator": "paginator-theme",
    "variables css del componente paginator": "paginator-theme",
    "variables css del componente paginator": "paginator-theme",
    "variables css y componente paginator": "paginator-theme",
    "variables css y componente paginator": "paginator-theme",
    "variables css + componente paginator": "paginator-theme",
    "variables css + componente paginator": "paginator-theme",
    "variables css mas componente paginator": "paginator-theme",
    "variables css mas componente paginator": "paginator-theme",
    "variables css más componente paginator": "paginator-theme",
    "variables css más componente paginator": "paginator-theme",
    "paginator css variables": "paginator-theme",
    "paginator component css variables": "paginator-theme",
    "css variables paginator component": "paginator-theme",
}