# agent: { description, prefixes }
component_mapping_input_text_agent = {
    "input-text-general": { # Nombre de Agente
        "description": "Consultas sobre componente input-text",
        "prefixes": ["input-text-interface", "input-text-definition", "input-text-usage"] # Nombre de archivos .md a consultar
    },
    "input-text-template": { # Nombre de Agente
        "description": "Consultas sobre componente input-text y sus templates",
        "prefixes": ["input-text-interface", "input-text-definition", "input-text-usage", "input-text-template"] # Nombre de archivos .md a consultar
    },
    "input-text-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente input-text",
        "prefixes": ["input-text-interface", "input-text-definition", "input-text-usage", "input-text-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_input_text_query = {
    # input-text-general
    "ilibtbinputtext": "input-text-general",
    "libtbinputtextmodule": "input-text-general",
    "lib-tb-input-text": "input-text-general",
    "entrada de texto": "input-text-general",
    "entrada de tipo texto": "input-text-general",
    "campo de texto": "input-text-general",
    "campo de tipo texto": "input-text-general",
    "input de texto": "input-text-general",
    "input text": "input-text-general",
    "input-text": "input-text-general",
    # input-text-template
    "input-text con template": "input-text-template",
    "input-text y template": "input-text-template",
    "input-text + template": "input-text-template",
    "input-text más template": "input-text-template",
    "input-text mas template": "input-text-template",
    "input-text con templates": "input-text-template",
    "input-text y templates": "input-text-template",
    "input-text + templates": "input-text-template",
    "input-text más templates": "input-text-template",
    "input-text mas templates": "input-text-template",
    "template en input-text": "input-text-template",
    "template con input-text": "input-text-template",
    "template de input-text": "input-text-template",
    "template + input-text": "input-text-template",
    "template más input-text": "input-text-template",
    "template mas input-text": "input-text-template",
    "templates en input-text": "input-text-template",
    "templates con input-text": "input-text-template",
    "templates de input-text": "input-text-template",
    "templates + input-text": "input-text-template",
    "templates más input-text": "input-text-template",
    "templates mas input-text": "input-text-template",
    "input text con template": "input-text-template",
    "input text y template": "input-text-template",
    "input text + template": "input-text-template",
    "input text más template": "input-text-template",
    "input text mas template": "input-text-template",
    "input text con templates": "input-text-template",
    "input text y templates": "input-text-template",
    "input text + templates": "input-text-template",
    "input text más templates": "input-text-template",
    "input text mas templates": "input-text-template",
    "template en input text": "input-text-template",
    "template con input text": "input-text-template",
    "template de input text": "input-text-template",
    "template + input text": "input-text-template",
    "template más input text": "input-text-template",
    "template mas input text": "input-text-template",
    "templates en input text": "input-text-template",
    "templates con input text": "input-text-template",
    "templates de input text": "input-text-template",
    "templates + input text": "input-text-template",
    "templates más input text": "input-text-template",
    "templates mas input text": "input-text-template",
    # input-text-theme
    "input text y variables css": "input-text-theme",
    "input-text y variables css": "input-text-theme",
    "input text + variables css": "input-text-theme",
    "input-text + variables css": "input-text-theme",
    "input text mas variables css": "input-text-theme",
    "input-text mas variables css": "input-text-theme",
    "input text más variables css": "input-text-theme",
    "input-text más variables css": "input-text-theme",
    "variables css del input text": "input-text-theme",
    "variables css del input-text": "input-text-theme",
    "variables css y input text": "input-text-theme",
    "variables css y input-text": "input-text-theme",
    "variables css + input text": "input-text-theme",
    "variables css + input-text": "input-text-theme",
    "variables css mas input text": "input-text-theme",
    "variables css mas input-text": "input-text-theme",
    "variables css más input text": "input-text-theme",
    "variables css más input-text": "input-text-theme",
    "variables css del componente input text": "input-text-theme",
    "variables css del componente input-text": "input-text-theme",
    "variables css y componente input text": "input-text-theme",
    "variables css y componente input-text": "input-text-theme",
    "variables css + componente input text": "input-text-theme",
    "variables css + componente input-text": "input-text-theme",
    "variables css mas componente input text": "input-text-theme",
    "variables css mas componente input-text": "input-text-theme",
    "variables css más componente input text": "input-text-theme",
    "variables css más componente input-text": "input-text-theme",
    "input text css variables": "input-text-theme",
    "input text component css variables": "input-text-theme",
    "css variables input text component": "input-text-theme",
    "input-text css variables": "input-text-theme",
    "input-text component css variables": "input-text-theme",
    "css variables input-text component": "input-text-theme",
}