# agent: { description, prefixes }
component_mapping_input_text_area_agent = {
    "input-text-area-general": { # Nombre de Agente
        "description": "Consultas sobre componente input-text-area",
        "prefixes": ["input-text-area-interface", "input-text-area-definition", "input-text-area-usage"] # Nombre de archivos .md a consultar
    },
    "input-text-area-template": { # Nombre de Agente
        "description": "Consultas sobre componente input-text-area y sus templates",
        "prefixes": ["input-text-area-interface", "input-text-area-definition", "input-text-area-usage", "input-text-area-template"] # Nombre de archivos .md a consultar
    },
    "input-text-area-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente input-text-area",
        "prefixes": ["input-text-area-interface", "input-text-area-definition", "input-text-area-usage", "input-text-area-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_input_text_area_query = {
    # input-text-area-general
    "ilibtbinputtextarea": "input-text-area-general",
    "libtbinputtextareamodule": "input-text-area-general",
    "lib-tb-input-text-area": "input-text-area-general",
    "area de texto": "input-text-area-general",
    "text area": "input-text-area-general",
    "input text area": "input-text-area-general",
    "input-text-area": "input-text-area-general",
    # input-text-area-template
    "input-text-area con template": "input-text-area-template",
    "input-text-area y template": "input-text-area-template",
    "input-text-area + template": "input-text-area-template",
    "input-text-area más template": "input-text-area-template",
    "input-text-area mas template": "input-text-area-template",
    "input-text-area con templates": "input-text-area-template",
    "input-text-area y templates": "input-text-area-template",
    "input-text-area + templates": "input-text-area-template",
    "input-text-area más templates": "input-text-area-template",
    "input-text-area mas templates": "input-text-area-template",
    "template en input-text-area": "input-text-area-template",
    "template con input-text-area": "input-text-area-template",
    "template de input-text-area": "input-text-area-template",
    "template + input-text-area": "input-text-area-template",
    "template más input-text-area": "input-text-area-template",
    "template mas input-text-area": "input-text-area-template",
    "templates en input-text-area": "input-text-area-template",
    "templates con input-text-area": "input-text-area-template",
    "templates de input-text-area": "input-text-area-template",
    "templates + input-text-area": "input-text-area-template",
    "templates más input-text-area": "input-text-area-template",
    "templates mas input-text-area": "input-text-area-template",
    "input text area con template": "input-text-area-template",
    "input text area y template": "input-text-area-template",
    "input text area + template": "input-text-area-template",
    "input text area más template": "input-text-area-template",
    "input text area mas template": "input-text-area-template",
    "input text area con templates": "input-text-area-template",
    "input text area y templates": "input-text-area-template",
    "input text area + templates": "input-text-area-template",
    "input text area más templates": "input-text-area-template",
    "input text area mas templates": "input-text-area-template",
    "template en input text area": "input-text-area-template",
    "template con input text area": "input-text-area-template",
    "template de input text area": "input-text-area-template",
    "template + input text area": "input-text-area-template",
    "template más input text area": "input-text-area-template",
    "template mas input text area": "input-text-area-template",
    "templates en input text area": "input-text-area-template",
    "templates con input text area": "input-text-area-template",
    "templates de input text area": "input-text-area-template",
    "templates + input text area": "input-text-area-template",
    "templates más input text area": "input-text-area-template",
    "templates mas input text area": "input-text-area-template",
    "text area con template": "input-text-area-template",
    "text area y template": "input-text-area-template",
    "text area + template": "input-text-area-template",
    "text area más template": "input-text-area-template",
    "text area mas template": "input-text-area-template",
    "text area con templates": "input-text-area-template",
    "text area y templates": "input-text-area-template",
    "text area + templates": "input-text-area-template",
    "text area más templates": "input-text-area-template",
    "text area mas templates": "input-text-area-template",
    "template en text area": "input-text-area-template",
    "template con text area": "input-text-area-template",
    "template del text area": "input-text-area-template",
    "template + text area": "input-text-area-template",
    "template más text area": "input-text-area-template",
    "template mas text area": "input-text-area-template",
    "templates en text area": "input-text-area-template",
    "templates con text area": "input-text-area-template",
    "templates del text area": "input-text-area-template",
    "templates + text area": "input-text-area-template",
    "templates más text area": "input-text-area-template",
    "templates mas text area": "input-text-area-template",
    "text area con template": "input-text-area-template",
    "text area y template": "input-text-area-template",
    "text area + template": "input-text-area-template",
    "text area más template": "input-text-area-template",
    "text area mas template": "input-text-area-template",
    "text area con templates": "input-text-area-template",
    "text area y templates": "input-text-area-template",
    "text area + templates": "input-text-area-template",
    "text area más templates": "input-text-area-template",
    "text area mas templates": "input-text-area-template",
    "template en text area": "input-text-area-template",
    "template con text area": "input-text-area-template",
    "template del text area": "input-text-area-template",
    "template + text area": "input-text-area-template",
    "template más text area": "input-text-area-template",
    "template mas text area": "input-text-area-template",
    "templates en text area": "input-text-area-template",
    "templates con text area": "input-text-area-template",
    "templates del text area": "input-text-area-template",
    "templates + text area": "input-text-area-template",
    "templates más text area": "input-text-area-template",
    "templates mas text area": "input-text-area-template",
    # input-text-area-theme
    "input text area y variables css": "input-text-area-theme",
    "input-text-area y variables css": "input-text-area-theme",
    "input text area + variables css": "input-text-area-theme",
    "input-text-area + variables css": "input-text-area-theme",
    "input text area mas variables css": "input-text-area-theme",
    "input-text-area mas variables css": "input-text-area-theme",
    "input text area más variables css": "input-text-area-theme",
    "input-text-area más variables css": "input-text-area-theme",
    "variables css del input text area": "input-text-area-theme",
    "variables css del input-text-area": "input-text-area-theme",
    "variables css y input text area": "input-text-area-theme",
    "variables css y input-text-area": "input-text-area-theme",
    "variables css + input text area": "input-text-area-theme",
    "variables css + input-text-area": "input-text-area-theme",
    "variables css mas input text area": "input-text-area-theme",
    "variables css mas input-text-area": "input-text-area-theme",
    "variables css más input text area": "input-text-area-theme",
    "variables css más input-text-area": "input-text-area-theme",
    "variables css del componente input text area": "input-text-area-theme",
    "variables css del componente input-text-area": "input-text-area-theme",
    "variables css y componente input text area": "input-text-area-theme",
    "variables css y componente input-text-area": "input-text-area-theme",
    "variables css + componente input text area": "input-text-area-theme",
    "variables css + componente input-text-area": "input-text-area-theme",
    "variables css mas componente input text area": "input-text-area-theme",
    "variables css mas componente input-text-area": "input-text-area-theme",
    "variables css más componente input text area": "input-text-area-theme",
    "variables css más componente input-text-area": "input-text-area-theme",
    "input text area css variables": "input-text-area-theme",
    "input text area component css variables": "input-text-area-theme",
    "css variables input text area component": "input-text-area-theme",
    "input-text-area css variables": "input-text-area-theme",
    "input-text-area component css variables": "input-text-area-theme",
    "css variables input-text-area component": "input-text-area-theme",
    "text area y variables css": "input-text-area-theme",
    "text area + variables css": "input-text-area-theme",
    "text area mas variables css": "input-text-area-theme",
    "text area más variables css": "input-text-area-theme",
    "variables css del text area": "input-text-area-theme",
    "variables css y text area": "input-text-area-theme",
    "variables css + text area": "input-text-area-theme",
    "variables css mas text area": "input-text-area-theme",
    "variables css más text area": "input-text-area-theme",
    "variables css del componente text area": "input-text-area-theme",
    "variables css y componente text area": "input-text-area-theme",
    "variables css + componente text area": "input-text-area-theme",
    "variables css mas componente text area": "input-text-area-theme",
    "variables css más componente text area": "input-text-area-theme",
    "text area css variables": "input-text-area-theme",
    "text area component css variables": "input-text-area-theme",
    "css variables text area component": "input-text-area-theme",
}