# agent: { description, prefixes }
component_mapping_indicator_gallery_agent = {
    "indicator-gallery-general": { # Nombre de Agente
        "description": "Consultas sobre componente indicator-gallery",
        "prefixes": ["indicator-gallery-interface", "indicator-gallery-definition", "indicator-gallery-usage"] # Nombre de archivos .md a consultar
    },
    "indicator-gallery-template": { # Nombre de Agente
        "description": "Consultas sobre componente indicator-gallery y sus templates",
        "prefixes": ["indicator-gallery-interface", "indicator-gallery-definition", "indicator-gallery-usage", "indicator-gallery-template"] # Nombre de archivos .md a consultar
    },
    "indicator-gallery-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente indicator-gallery",
        "prefixes": ["indicator-gallery-interface", "indicator-gallery-definition", "indicator-gallery-usage", "indicator-gallery-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_indicator_gallery_query = {
    # indicator-gallery-general
    "ilibtbindicatorgallery": "indicator-gallery-general",
    "libtbindicatorgallerymodule": "indicator-gallery-general",
    "lib-tb-indicator-gallery": "indicator-gallery-general",
    "indicador de galeria": "indicator-gallery-general",
    "indicador de galería": "indicator-gallery-general",
    "indicator gallery": "indicator-gallery-general",
    "indicator-gallery": "indicator-gallery-general",
    # indicator-gallery-template
    "indicador de galeria con template": "indicator-gallery-template",
    "indicador de galeria y template": "indicator-gallery-template",
    "indicador de galeria + template": "indicator-gallery-template",
    "indicador de galeria más template": "indicator-gallery-template",
    "indicador de galeria mas template": "indicator-gallery-template",
    "indicador de galeria con templates": "indicator-gallery-template",
    "indicador de galeria y templates": "indicator-gallery-template",
    "indicador de galeria + templates": "indicator-gallery-template",
    "indicador de galeria más templates": "indicator-gallery-template",
    "indicador de galeria mas templates": "indicator-gallery-template",
    "template y indicador de galeria": "indicator-gallery-template",
    "template e indicador de galeria": "indicator-gallery-template",
    "template en indicador de galeria": "indicator-gallery-template",
    "template con indicador de galeria": "indicator-gallery-template",
    "template de indicador de galeria": "indicator-gallery-template",
    "template del indicador de galeria": "indicator-gallery-template",
    "template + indicador de galeria": "indicator-gallery-template",
    "template más indicador de galeria": "indicator-gallery-template",
    "template mas indicador de galeria": "indicator-gallery-template",
    "templates en indicador de galeria": "indicator-gallery-template",
    "templates con indicador de galeria": "indicator-gallery-template",
    "templates de indicador de galeria": "indicator-gallery-template",
    "templates del indicador de galeria": "indicator-gallery-template",
    "templates + indicador de galeria": "indicator-gallery-template",
    "templates más indicador de galeria": "indicator-gallery-template",
    "templates mas indicador de galeria": "indicator-gallery-template",
    "indicador de galería con template": "indicator-gallery-template",
    "indicador de galería y template": "indicator-gallery-template",
    "indicador de galería + template": "indicator-gallery-template",
    "indicador de galería más template": "indicator-gallery-template",
    "indicador de galería mas template": "indicator-gallery-template",
    "indicador de galería con templates": "indicator-gallery-template",
    "indicador de galería y templates": "indicator-gallery-template",
    "indicador de galería + templates": "indicator-gallery-template",
    "indicador de galería más templates": "indicator-gallery-template",
    "indicador de galería mas templates": "indicator-gallery-template",
    "template y indicador de galería": "indicator-gallery-template",
    "template e indicador de galería": "indicator-gallery-template",
    "template en indicador de galería": "indicator-gallery-template",
    "template con indicador de galería": "indicator-gallery-template",
    "template de indicador de galería": "indicator-gallery-template",
    "template del indicador de galería": "indicator-gallery-template",
    "template + indicador de galería": "indicator-gallery-template",
    "template más indicador de galería": "indicator-gallery-template",
    "template mas indicador de galería": "indicator-gallery-template",
    "templates en indicador de galería": "indicator-gallery-template",
    "templates con indicador de galería": "indicator-gallery-template",
    "templates de indicador de galería": "indicator-gallery-template",
    "templates del indicador de galería": "indicator-gallery-template",
    "templates + indicador de galería": "indicator-gallery-template",
    "templates más indicador de galería": "indicator-gallery-template",
    "templates mas indicador de galería": "indicator-gallery-template",
    "indicator-gallery con template": "indicator-gallery-template",
    "indicator-gallery y template": "indicator-gallery-template",
    "indicator-gallery + template": "indicator-gallery-template",
    "indicator-gallery más template": "indicator-gallery-template",
    "indicator-gallery mas template": "indicator-gallery-template",
    "indicator-gallery con templates": "indicator-gallery-template",
    "indicator-gallery y templates": "indicator-gallery-template",
    "indicator-gallery + templates": "indicator-gallery-template",
    "indicator-gallery más templates": "indicator-gallery-template",
    "indicator-gallery mas templates": "indicator-gallery-template",
    "template en indicator-gallery": "indicator-gallery-template",
    "template con indicator-gallery": "indicator-gallery-template",
    "template de indicator-gallery": "indicator-gallery-template",
    "template + indicator-gallery": "indicator-gallery-template",
    "template más indicator-gallery": "indicator-gallery-template",
    "template mas indicator-gallery": "indicator-gallery-template",
    "templates en indicator-gallery": "indicator-gallery-template",
    "templates con indicator-gallery": "indicator-gallery-template",
    "templates de indicator-gallery": "indicator-gallery-template",
    "templates + indicator-gallery": "indicator-gallery-template",
    "templates más indicator-gallery": "indicator-gallery-template",
    "templates mas indicator-gallery": "indicator-gallery-template",
    "indicator gallery con template": "indicator-gallery-template",
    "indicator gallery y template": "indicator-gallery-template",
    "indicator gallery + template": "indicator-gallery-template",
    "indicator gallery más template": "indicator-gallery-template",
    "indicator gallery mas template": "indicator-gallery-template",
    "indicator gallery con templates": "indicator-gallery-template",
    "indicator gallery y templates": "indicator-gallery-template",
    "indicator gallery + templates": "indicator-gallery-template",
    "indicator gallery más templates": "indicator-gallery-template",
    "indicator gallery mas templates": "indicator-gallery-template",
    "template en indicator gallery": "indicator-gallery-template",
    "template con indicator gallery": "indicator-gallery-template",
    "template de indicator gallery": "indicator-gallery-template",
    "template del indicator gallery": "indicator-gallery-template",
    "template + indicator gallery": "indicator-gallery-template",
    "template más indicator gallery": "indicator-gallery-template",
    "template mas indicator gallery": "indicator-gallery-template",
    "templates en indicator gallery": "indicator-gallery-template",
    "templates con indicator gallery": "indicator-gallery-template",
    "templates de indicator gallery": "indicator-gallery-template",
    "templates del indicator gallery": "indicator-gallery-template",
    "templates + indicator gallery": "indicator-gallery-template",
    "templates más indicator gallery": "indicator-gallery-template",
    "templates mas indicator gallery": "indicator-gallery-template",
    "indicator-gallery template": "indicator-gallery-template",
    "indicator-gallery templates": "indicator-gallery-template",
    "indicator gallery template": "indicator-gallery-template",
    "indicator gallery templates": "indicator-gallery-template",
    # indicator-gallery-theme
    "indicador de galeria y variables css": "indicator-gallery-theme",
    "indicador de galeria y variables css": "indicator-gallery-theme",
    "indicador de galeria + variables css": "indicator-gallery-theme",
    "indicador de galeria + variables css": "indicator-gallery-theme",
    "indicador de galeria mas variables css": "indicator-gallery-theme",
    "indicador de galeria mas variables css": "indicator-gallery-theme",
    "indicador de galeria más variables css": "indicator-gallery-theme",
    "indicador de galeria más variables css": "indicator-gallery-theme",
    "variables css del indicador de galeria": "indicator-gallery-theme",
    "variables css y indicador de galeria": "indicator-gallery-theme",
    "variables css + indicador de galeria": "indicator-gallery-theme",
    "variables css mas indicador de galeria": "indicator-gallery-theme",
    "variables css más indicador de galeria": "indicator-gallery-theme",
    "variables css del componente indicador de galeria": "indicator-gallery-theme",
    "variables css y componente indicador de galeria": "indicator-gallery-theme",
    "variables css + componente indicador de galeria": "indicator-gallery-theme",
    "variables css mas componente indicador de galeria": "indicator-gallery-theme",
    "variables css más componente indicador de galeria": "indicator-gallery-theme",
    "indicador de galería y variables css": "indicator-gallery-theme",
    "indicador de galería + variables css": "indicator-gallery-theme",
    "indicador de galería mas variables css": "indicator-gallery-theme",
    "indicador de galería más variables css": "indicator-gallery-theme",
    "variables css del indicador de galería": "indicator-gallery-theme",
    "variables css y indicador de galería": "indicator-gallery-theme",
    "variables css + indicador de galería": "indicator-gallery-theme",
    "variables css mas indicador de galería": "indicator-gallery-theme",
    "variables css más indicador de galería": "indicator-gallery-theme",
    "variables css del componente indicador de galería": "indicator-gallery-theme",
    "variables css y componente indicador de galería": "indicator-gallery-theme",
    "variables css + componente indicador de galería": "indicator-gallery-theme",
    "variables css mas componente indicador de galería": "indicator-gallery-theme",
    "variables css más componente indicador de galería": "indicator-gallery-theme",
    "indicator gallery y variables css": "indicator-gallery-theme",
    "indicator-gallery y variables css": "indicator-gallery-theme",
    "indicator gallery + variables css": "indicator-gallery-theme",
    "indicator-gallery + variables css": "indicator-gallery-theme",
    "indicator gallery mas variables css": "indicator-gallery-theme",
    "indicator-gallery mas variables css": "indicator-gallery-theme",
    "indicator gallery más variables css": "indicator-gallery-theme",
    "indicator-gallery más variables css": "indicator-gallery-theme",
    "variables css del indicator gallery": "indicator-gallery-theme",
    "variables css del indicator-gallery": "indicator-gallery-theme",
    "variables css y indicator gallery": "indicator-gallery-theme",
    "variables css y indicator-gallery": "indicator-gallery-theme",
    "variables css + indicator gallery": "indicator-gallery-theme",
    "variables css + indicator-gallery": "indicator-gallery-theme",
    "variables css mas indicator gallery": "indicator-gallery-theme",
    "variables css mas indicator-gallery": "indicator-gallery-theme",
    "variables css más indicator gallery": "indicator-gallery-theme",
    "variables css más indicator-gallery": "indicator-gallery-theme",
    "variables css del componente indicator gallery": "indicator-gallery-theme",
    "variables css del componente indicator-gallery": "indicator-gallery-theme",
    "variables css y componente indicator gallery": "indicator-gallery-theme",
    "variables css y componente indicator-gallery": "indicator-gallery-theme",
    "variables css + componente indicator gallery": "indicator-gallery-theme",
    "variables css + componente indicator-gallery": "indicator-gallery-theme",
    "variables css mas componente indicator gallery": "indicator-gallery-theme",
    "variables css mas componente indicator-gallery": "indicator-gallery-theme",
    "variables css más componente indicator gallery": "indicator-gallery-theme",
    "variables css más componente indicator-gallery": "indicator-gallery-theme",
    "indicator gallery css variables": "indicator-gallery-theme",
    "indicator gallery component css variables": "indicator-gallery-theme",
    "css variables indicator gallery component": "indicator-gallery-theme",
    "indicator-gallery css variables": "indicator-gallery-theme",
    "indicator-gallery component css variables": "indicator-gallery-theme",
    "css variables indicator-gallery component": "indicator-gallery-theme",
}