# agent: { description, prefixes }
component_mapping_calendar_agent = {
    "calendar-general": { # Nombre de Agente
        "description": "Consultas sobre componente calendar",
        "prefixes": ["calendar-interface", "calendar-definition", "calendar-usage"] # Nombre de archivos .md a consultar
    },
    "calendar-template": { # Nombre de Agente
        "description": "Consultas sobre componente calendar y sus templates",
        "prefixes": ["calendar-interface", "calendar-definition", "calendar-usage", "calendar-template"] # Nombre de archivos .md a consultar
    },
    "calendar-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente calendar",
        "prefixes": ["calendar-interface", "calendar-definition", "calendar-usage", "calendar-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_calendar_query = {
    # calendar-general
    "ilibtbcalendar": "calendar-general",
    "libtbcalendarmodule": "calendar-general",
    "lib-tb-calendar": "calendar-general",
    "calendario": "calendar-general",
    "calendar": "calendar-general",
    # calendar-template
    "calendario con template": "calendar-template",
    "calendario y template": "calendar-template",
    "calendario + template": "calendar-template",
    "calendario más template": "calendar-template",
    "calendario mas template": "calendar-template",
    "calendario con templates": "calendar-template",
    "calendario y templates": "calendar-template",
    "calendario + templates": "calendar-template",
    "calendario más templates": "calendar-template",
    "calendario mas templates": "calendar-template",
    "template y calendario": "calendar-template",
    "template en calendario": "calendar-template",
    "template con calendario": "calendar-template",
    "template de calendario": "calendar-template",
    "template + calendario": "calendar-template",
    "template más calendario": "calendar-template",
    "template mas calendario": "calendar-template",
    "templates en calendario": "calendar-template",
    "templates con calendario": "calendar-template",
    "templates de calendario": "calendar-template",
    "templates + calendario": "calendar-template",
    "templates más calendario": "calendar-template",
    "templates mas calendario": "calendar-template",
    "calendar con template": "calendar-template",
    "calendar y template": "calendar-template",
    "calendar + template": "calendar-template",
    "calendar más template": "calendar-template",
    "calendar mas template": "calendar-template",
    "calendar con templates": "calendar-template",
    "calendar y templates": "calendar-template",
    "calendar + templates": "calendar-template",
    "calendar más templates": "calendar-template",
    "calendar mas templates": "calendar-template",
    "template en calendar": "calendar-template",
    "template con calendar": "calendar-template",
    "template de calendar": "calendar-template",
    "template + calendar": "calendar-template",
    "template más calendar": "calendar-template",
    "template mas calendar": "calendar-template",
    "templates en calendar": "calendar-template",
    "templates con calendar": "calendar-template",
    "templates de calendar": "calendar-template",
    "templates + calendar": "calendar-template",
    "templates más calendar": "calendar-template",
    "templates mas calendar": "calendar-template",
    # calendar-theme
    "calendario y variables css": "calendar-theme",
    "calendario y variables css": "calendar-theme",
    "calendario + variables css": "calendar-theme",
    "calendario + variables css": "calendar-theme",
    "calendario mas variables css": "calendar-theme",
    "calendario mas variables css": "calendar-theme",
    "calendario más variables css": "calendar-theme",
    "calendario más variables css": "calendar-theme",
    "variables css del calendario": "calendar-theme",
    "variables css del calendario": "calendar-theme",
    "variables css y calendario": "calendar-theme",
    "variables css y calendario": "calendar-theme",
    "variables css + calendario": "calendar-theme",
    "variables css + calendario": "calendar-theme",
    "variables css mas calendario": "calendar-theme",
    "variables css mas calendario": "calendar-theme",
    "variables css más calendario": "calendar-theme",
    "variables css más calendario": "calendar-theme",
    "variables css del componente calendario": "calendar-theme",
    "variables css del componente calendario": "calendar-theme",
    "variables css y componente calendario": "calendar-theme",
    "variables css y componente calendario": "calendar-theme",
    "variables css + componente calendario": "calendar-theme",
    "variables css + componente calendario": "calendar-theme",
    "variables css mas componente calendario": "calendar-theme",
    "variables css mas componente calendario": "calendar-theme",
    "variables css más componente calendario": "calendar-theme",
    "variables css más componente calendario": "calendar-theme",
    "calendar y variables css": "calendar-theme",
    "calendar y variables css": "calendar-theme",
    "calendar + variables css": "calendar-theme",
    "calendar + variables css": "calendar-theme",
    "calendar mas variables css": "calendar-theme",
    "calendar mas variables css": "calendar-theme",
    "calendar más variables css": "calendar-theme",
    "calendar más variables css": "calendar-theme",
    "variables css del calendar": "calendar-theme",
    "variables css del calendar": "calendar-theme",
    "variables css y calendar": "calendar-theme",
    "variables css y calendar": "calendar-theme",
    "variables css + calendar": "calendar-theme",
    "variables css + calendar": "calendar-theme",
    "variables css mas calendar": "calendar-theme",
    "variables css mas calendar": "calendar-theme",
    "variables css más calendar": "calendar-theme",
    "variables css más calendar": "calendar-theme",
    "variables css del componente calendar": "calendar-theme",
    "variables css del componente calendar": "calendar-theme",
    "variables css y componente calendar": "calendar-theme",
    "variables css y componente calendar": "calendar-theme",
    "variables css + componente calendar": "calendar-theme",
    "variables css + componente calendar": "calendar-theme",
    "variables css mas componente calendar": "calendar-theme",
    "variables css mas componente calendar": "calendar-theme",
    "variables css más componente calendar": "calendar-theme",
    "variables css más componente calendar": "calendar-theme",
    "calendar css variables": "calendar-theme",
    "calendar component css variables": "calendar-theme",
    "css variables calendar component": "calendar-theme",
    "calendar css variables": "calendar-theme",
    "calendar component css variables": "calendar-theme",
    "css variables calendar component": "calendar-theme",
}