# agent: { description, prefixes }
component_mapping_file_upload_field_agent = {
    "file-upload-field-general": { # Nombre de Agente
        "description": "Consultas sobre componente file-upload-field",
        "prefixes": ["file-upload-field-interface", "file-upload-field-definition", "file-upload-field-usage"] # Nombre de archivos .md a consultar
    },
    "file-upload-field-template": { # Nombre de Agente
        "description": "Consultas sobre componente file-upload-field y sus templates",
        "prefixes": ["file-upload-field-interface", "file-upload-field-definition", "file-upload-field-usage", "file-upload-field-template"] # Nombre de archivos .md a consultar
    },
    "file-upload-field-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente file-upload-field",
        "prefixes": ["file-upload-field-interface", "file-upload-field-definition", "file-upload-field-usage", "file-upload-field-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_file_upload_field_query = {
    # file-upload-field-general
    "ilibtbfileuploadfield": "file-upload-field-general",
    "libtbfileuploadfieldmodule": "file-upload-field-general",
    "lib-tb-file-upload-field": "file-upload-field-general",
    "subir archivos": "file-upload-field-general",
    "file upload field": "file-upload-field-general",
    "file-upload-field": "file-upload-field-general",
    # file-upload-field-template
    "file-upload-field con template": "file-upload-field-template",
    "file-upload-field y template": "file-upload-field-template",
    "file-upload-field + template": "file-upload-field-template",
    "file-upload-field más template": "file-upload-field-template",
    "file-upload-field mas template": "file-upload-field-template",
    "file-upload-field con templates": "file-upload-field-template",
    "file-upload-field y templates": "file-upload-field-template",
    "file-upload-field + templates": "file-upload-field-template",
    "file-upload-field más templates": "file-upload-field-template",
    "file-upload-field mas templates": "file-upload-field-template",
    "template en file-upload-field": "file-upload-field-template",
    "template con file-upload-field": "file-upload-field-template",
    "template de file-upload-field": "file-upload-field-template",
    "template + file-upload-field": "file-upload-field-template",
    "template más file-upload-field": "file-upload-field-template",
    "template mas file-upload-field": "file-upload-field-template",
    "templates en file-upload-field": "file-upload-field-template",
    "templates con file-upload-field": "file-upload-field-template",
    "templates de file-upload-field": "file-upload-field-template",
    "templates + file-upload-field": "file-upload-field-template",
    "templates más file-upload-field": "file-upload-field-template",
    "templates mas file-upload-field": "file-upload-field-template",
    "file upload field con template": "file-upload-field-template",
    "file upload field y template": "file-upload-field-template",
    "file upload field + template": "file-upload-field-template",
    "file upload field más template": "file-upload-field-template",
    "file upload field mas template": "file-upload-field-template",
    "file upload field con templates": "file-upload-field-template",
    "file upload field y templates": "file-upload-field-template",
    "file upload field + templates": "file-upload-field-template",
    "file upload field más templates": "file-upload-field-template",
    "file upload field mas templates": "file-upload-field-template",
    "template en file upload field": "file-upload-field-template",
    "template con file upload field": "file-upload-field-template",
    "template de file upload field": "file-upload-field-template",
    "template + file upload field": "file-upload-field-template",
    "template más file upload field": "file-upload-field-template",
    "template mas file upload field": "file-upload-field-template",
    "templates en file upload field": "file-upload-field-template",
    "templates con file upload field": "file-upload-field-template",
    "templates de file upload field": "file-upload-field-template",
    "templates + file upload field": "file-upload-field-template",
    "templates más file upload field": "file-upload-field-template",
    "templates mas file upload field": "file-upload-field-template",
    "subir archivos con template": "file-upload-field-template",
    "subir archivos y template": "file-upload-field-template",
    "subir archivos + template": "file-upload-field-template",
    "subir archivos más template": "file-upload-field-template",
    "subir archivos mas template": "file-upload-field-template",
    "subir archivos con templates": "file-upload-field-template",
    "subir archivos y templates": "file-upload-field-template",
    "subir archivos + templates": "file-upload-field-template",
    "subir archivos más templates": "file-upload-field-template",
    "subir archivos mas templates": "file-upload-field-template",
    "template en subir archivos": "file-upload-field-template",
    "template con subir archivos": "file-upload-field-template",
    "template del subir archivos": "file-upload-field-template",
    "template + subir archivos": "file-upload-field-template",
    "template más subir archivos": "file-upload-field-template",
    "template mas subir archivos": "file-upload-field-template",
    "templates en subir archivos": "file-upload-field-template",
    "templates con subir archivos": "file-upload-field-template",
    "templates del subir archivos": "file-upload-field-template",
    "templates + subir archivos": "file-upload-field-template",
    "templates más subir archivos": "file-upload-field-template",
    "templates mas subir archivos": "file-upload-field-template",
    "subir archivos con template": "file-upload-field-template",
    "subir archivos y template": "file-upload-field-template",
    "subir archivos + template": "file-upload-field-template",
    "subir archivos más template": "file-upload-field-template",
    "subir archivos mas template": "file-upload-field-template",
    "subir archivos con templates": "file-upload-field-template",
    "subir archivos y templates": "file-upload-field-template",
    "subir archivos + templates": "file-upload-field-template",
    "subir archivos más templates": "file-upload-field-template",
    "subir archivos mas templates": "file-upload-field-template",
    "template en subir archivos": "file-upload-field-template",
    "template con subir archivos": "file-upload-field-template",
    "template del subir archivos": "file-upload-field-template",
    "template + subir archivos": "file-upload-field-template",
    "template más subir archivos": "file-upload-field-template",
    "template mas subir archivos": "file-upload-field-template",
    "templates en subir archivos": "file-upload-field-template",
    "templates con subir archivos": "file-upload-field-template",
    "templates del subir archivos": "file-upload-field-template",
    "templates + subir archivos": "file-upload-field-template",
    "templates más subir archivos": "file-upload-field-template",
    "templates mas subir archivos": "file-upload-field-template",
    # file-upload-field-theme
    "file upload field y variables css": "file-upload-field-theme",
    "file-upload-field y variables css": "file-upload-field-theme",
    "file upload field + variables css": "file-upload-field-theme",
    "file-upload-field + variables css": "file-upload-field-theme",
    "file upload field mas variables css": "file-upload-field-theme",
    "file-upload-field mas variables css": "file-upload-field-theme",
    "file upload field más variables css": "file-upload-field-theme",
    "file-upload-field más variables css": "file-upload-field-theme",
    "variables css del file upload field": "file-upload-field-theme",
    "variables css del file-upload-field": "file-upload-field-theme",
    "variables css y file upload field": "file-upload-field-theme",
    "variables css y file-upload-field": "file-upload-field-theme",
    "variables css + file upload field": "file-upload-field-theme",
    "variables css + file-upload-field": "file-upload-field-theme",
    "variables css mas file upload field": "file-upload-field-theme",
    "variables css mas file-upload-field": "file-upload-field-theme",
    "variables css más file upload field": "file-upload-field-theme",
    "variables css más file-upload-field": "file-upload-field-theme",
    "variables css del componente file upload field": "file-upload-field-theme",
    "variables css del componente file-upload-field": "file-upload-field-theme",
    "variables css y componente file upload field": "file-upload-field-theme",
    "variables css y componente file-upload-field": "file-upload-field-theme",
    "variables css + componente file upload field": "file-upload-field-theme",
    "variables css + componente file-upload-field": "file-upload-field-theme",
    "variables css mas componente file upload field": "file-upload-field-theme",
    "variables css mas componente file-upload-field": "file-upload-field-theme",
    "variables css más componente file upload field": "file-upload-field-theme",
    "variables css más componente file-upload-field": "file-upload-field-theme",
    "file upload field css variables": "file-upload-field-theme",
    "file upload field component css variables": "file-upload-field-theme",
    "css variables file upload field component": "file-upload-field-theme",
    "file-upload-field css variables": "file-upload-field-theme",
    "file-upload-field component css variables": "file-upload-field-theme",
    "css variables file-upload-field component": "file-upload-field-theme",
    "subir archivos y variables css": "file-upload-field-theme",
    "subir archivos + variables css": "file-upload-field-theme",
    "subir archivos mas variables css": "file-upload-field-theme",
    "subir archivos más variables css": "file-upload-field-theme",
    "variables css del subir archivos": "file-upload-field-theme",
    "variables css y subir archivos": "file-upload-field-theme",
    "variables css + subir archivos": "file-upload-field-theme",
    "variables css mas subir archivos": "file-upload-field-theme",
    "variables css más subir archivos": "file-upload-field-theme",
    "variables css del componente subir archivos": "file-upload-field-theme",
    "variables css y componente subir archivos": "file-upload-field-theme",
    "variables css + componente subir archivos": "file-upload-field-theme",
    "variables css mas componente subir archivos": "file-upload-field-theme",
    "variables css más componente subir archivos": "file-upload-field-theme",
}