# agent: { description, prefixes }
component_mapping_modal_notification_agent = {
    "modal-notification-general": { # Nombre de Agente
        "description": "Consultas sobre componente modal-notification",
        "prefixes": ["modal-notification-interface", "modal-notification-definition", "modal-notification-usage"] # Nombre de archivos .md a consultar
    },
    "modal-notification-template": { # Nombre de Agente
        "description": "Consultas sobre componente modal-notification y sus templates",
        "prefixes": ["modal-notification-interface", "modal-notification-definition", "modal-notification-usage", "modal-notification-template"] # Nombre de archivos .md a consultar
    },
    "modal-notification-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente modal-notification",
        "prefixes": ["modal-notification-interface", "modal-notification-definition", "modal-notification-usage", "modal-notification-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_modal_notification_query = {
    # modal-notification-general
    "ilibtbmodalnotification": "modal-notification-general",
    "libtbmodalnotificationmodule": "modal-notification-general",
    "lib-tb-modal-notification": "modal-notification-general",
    "modal notification": "modal-notification-general",
    "modal-notification": "modal-notification-general",
    # modal-notification-template
    "modal-notification con template": "modal-notification-template",
    "modal-notification y template": "modal-notification-template",
    "modal-notification + template": "modal-notification-template",
    "modal-notification más template": "modal-notification-template",
    "modal-notification mas template": "modal-notification-template",
    "modal-notification con templates": "modal-notification-template",
    "modal-notification y templates": "modal-notification-template",
    "modal-notification + templates": "modal-notification-template",
    "modal-notification más templates": "modal-notification-template",
    "modal-notification mas templates": "modal-notification-template",
    "template y modal-notification": "modal-notification-template",
    "template en modal-notification": "modal-notification-template",
    "template con modal-notification": "modal-notification-template",
    "template de modal-notification": "modal-notification-template",
    "template + modal-notification": "modal-notification-template",
    "template más modal-notification": "modal-notification-template",
    "template mas modal-notification": "modal-notification-template",
    "templates y modal-notification": "modal-notification-template",
    "templates en modal-notification": "modal-notification-template",
    "templates con modal-notification": "modal-notification-template",
    "templates de modal-notification": "modal-notification-template",
    "templates + modal-notification": "modal-notification-template",
    "templates más modal-notification": "modal-notification-template",
    "templates mas modal-notification": "modal-notification-template",
    "modal notification con template": "modal-notification-template",
    "modal notification y template": "modal-notification-template",
    "modal notification + template": "modal-notification-template",
    "modal notification más template": "modal-notification-template",
    "modal notification mas template": "modal-notification-template",
    "modal notification con templates": "modal-notification-template",
    "modal notification y templates": "modal-notification-template",
    "modal notification + templates": "modal-notification-template",
    "modal notification más templates": "modal-notification-template",
    "modal notification mas templates": "modal-notification-template",
    "template y modal notification": "modal-notification-template",
    "template en modal notification": "modal-notification-template",
    "template con modal notification": "modal-notification-template",
    "template de modal notification": "modal-notification-template",
    "template del modal notification": "modal-notification-template",
    "template + modal notification": "modal-notification-template",
    "template más modal notification": "modal-notification-template",
    "template mas modal notification": "modal-notification-template",
    "templates y modal notification": "modal-notification-template",
    "templates en modal notification": "modal-notification-template",
    "templates con modal notification": "modal-notification-template",
    "templates de modal notification": "modal-notification-template",
    "templates del modal notification": "modal-notification-template",
    "templates + modal notification": "modal-notification-template",
    "templates más modal notification": "modal-notification-template",
    "templates mas modal notification": "modal-notification-template",
    # modal-notification-theme
    "modal notification y variables css": "modal-notification-theme",
    "modal-notification y variables css": "modal-notification-theme",
    "modal notification + variables css": "modal-notification-theme",
    "modal-notification + variables css": "modal-notification-theme",
    "modal notification mas variables css": "modal-notification-theme",
    "modal-notification mas variables css": "modal-notification-theme",
    "modal notification más variables css": "modal-notification-theme",
    "modal-notification más variables css": "modal-notification-theme",
    "variables css del modal notification": "modal-notification-theme",
    "variables css del modal-notification": "modal-notification-theme",
    "variables css y modal notification": "modal-notification-theme",
    "variables css y modal-notification": "modal-notification-theme",
    "variables css + modal notification": "modal-notification-theme",
    "variables css + modal-notification": "modal-notification-theme",
    "variables css mas modal notification": "modal-notification-theme",
    "variables css mas modal-notification": "modal-notification-theme",
    "variables css más modal notification": "modal-notification-theme",
    "variables css más modal-notification": "modal-notification-theme",
    "variables css del componente modal notification": "modal-notification-theme",
    "variables css del componente modal-notification": "modal-notification-theme",
    "variables css y componente modal notification": "modal-notification-theme",
    "variables css y componente modal-notification": "modal-notification-theme",
    "variables css + componente modal notification": "modal-notification-theme",
    "variables css + componente modal-notification": "modal-notification-theme",
    "variables css mas componente modal notification": "modal-notification-theme",
    "variables css mas componente modal-notification": "modal-notification-theme",
    "variables css más componente modal notification": "modal-notification-theme",
    "variables css más componente modal-notification": "modal-notification-theme",
    "modal notification css variables": "modal-notification-theme",
    "modal notification component css variables": "modal-notification-theme",
    "css variables modal notification component": "modal-notification-theme",
    "modal-notification css variables": "modal-notification-theme",
    "modal-notification component css variables": "modal-notification-theme",
    "css variables modal-notification component": "modal-notification-theme",
}