# agent: { description, prefixes }
component_mapping_context_menu_agent = {
    "context-menu-general": { # Nombre de Agente
        "description": "Consultas sobre componente context-menu",
        "prefixes": ["context-menu-interface", "context-menu-definition", "context-menu-usage"] # Nombre de archivos .md a consultar
    },
    "context-menu-template": { # Nombre de Agente
        "description": "Consultas sobre componente context-menu y sus templates",
        "prefixes": ["context-menu-interface", "context-menu-definition", "context-menu-usage", "context-menu-template"] # Nombre de archivos .md a consultar
    },
    "context-menu-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente context-menu",
        "prefixes": ["context-menu-interface", "context-menu-definition", "context-menu-usage", "context-menu-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_context_menu_query = {
    # context-menu-general
    "ilibtbcontextmenu": "context-menu-general",
    "libtbcontextmenumodule": "context-menu-general",
    "lib-tb-context-menu": "context-menu-general",
    "context menu": "context-menu-general",
    "context-menu": "context-menu-general",
    # context-menu-template
    "context-menu con template": "context-menu-template",
    "context-menu y template": "context-menu-template",
    "context-menu + template": "context-menu-template",
    "context-menu más template": "context-menu-template",
    "context-menu mas template": "context-menu-template",
    "context-menu con templates": "context-menu-template",
    "context-menu y templates": "context-menu-template",
    "context-menu + templates": "context-menu-template",
    "context-menu más templates": "context-menu-template",
    "context-menu mas templates": "context-menu-template",
    "template en context-menu": "context-menu-template",
    "template con context-menu": "context-menu-template",
    "template de context-menu": "context-menu-template",
    "template + context-menu": "context-menu-template",
    "template más context-menu": "context-menu-template",
    "template mas context-menu": "context-menu-template",
    "templates en context-menu": "context-menu-template",
    "templates con context-menu": "context-menu-template",
    "templates de context-menu": "context-menu-template",
    "templates + context-menu": "context-menu-template",
    "templates más context-menu": "context-menu-template",
    "templates mas context-menu": "context-menu-template",
    "context menu con template": "context-menu-template",
    "context menu y template": "context-menu-template",
    "context menu + template": "context-menu-template",
    "context menu más template": "context-menu-template",
    "context menu mas template": "context-menu-template",
    "context menu con templates": "context-menu-template",
    "context menu y templates": "context-menu-template",
    "context menu + templates": "context-menu-template",
    "context menu más templates": "context-menu-template",
    "context menu mas templates": "context-menu-template",
    "template en context menu": "context-menu-template",
    "template con context menu": "context-menu-template",
    "template de context menu": "context-menu-template",
    "template del context menu": "context-menu-template",
    "template + context menu": "context-menu-template",
    "template más context menu": "context-menu-template",
    "template mas context menu": "context-menu-template",
    "templates en context menu": "context-menu-template",
    "templates con context menu": "context-menu-template",
    "templates de context menu": "context-menu-template",
    "templates del context menu": "context-menu-template",
    "templates + context menu": "context-menu-template",
    "templates más context menu": "context-menu-template",
    "templates mas context menu": "context-menu-template",
    # context-menu-theme
    "context menu y variables css": "context-menu-theme",
    "context-menu y variables css": "context-menu-theme",
    "context menu + variables css": "context-menu-theme",
    "context-menu + variables css": "context-menu-theme",
    "context menu mas variables css": "context-menu-theme",
    "context-menu mas variables css": "context-menu-theme",
    "context menu más variables css": "context-menu-theme",
    "context-menu más variables css": "context-menu-theme",
    "variables css del context menu": "context-menu-theme",
    "variables css del context-menu": "context-menu-theme",
    "variables css y context menu": "context-menu-theme",
    "variables css y context-menu": "context-menu-theme",
    "variables css + context menu": "context-menu-theme",
    "variables css + context-menu": "context-menu-theme",
    "variables css mas context menu": "context-menu-theme",
    "variables css mas context-menu": "context-menu-theme",
    "variables css más context menu": "context-menu-theme",
    "variables css más context-menu": "context-menu-theme",
    "variables css del componente context menu": "context-menu-theme",
    "variables css del componente context-menu": "context-menu-theme",
    "variables css y componente context menu": "context-menu-theme",
    "variables css y componente context-menu": "context-menu-theme",
    "variables css + componente context menu": "context-menu-theme",
    "variables css + componente context-menu": "context-menu-theme",
    "variables css mas componente context menu": "context-menu-theme",
    "variables css mas componente context-menu": "context-menu-theme",
    "variables css más componente context menu": "context-menu-theme",
    "variables css más componente context-menu": "context-menu-theme",
    "context menu css variables": "context-menu-theme",
    "context menu component css variables": "context-menu-theme",
    "css variables context menu component": "context-menu-theme",
    "context-menu css variables": "context-menu-theme",
    "context-menu component css variables": "context-menu-theme",
    "css variables context-menu component": "context-menu-theme",
}