# agent: { description, prefixes }
component_mapping_search_agent = {
    "search-general": { # Nombre de Agente
        "description": "Consultas sobre componente search",
        "prefixes": ["search-interface", "search-definition", "search-usage"] # Nombre de archivos .md a consultar
    },
    "search-template": { # Nombre de Agente
        "description": "Consultas sobre componente search y sus templates",
        "prefixes": ["search-interface", "search-definition", "search-usage", "search-template"] # Nombre de archivos .md a consultar
    },
    "search-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente search",
        "prefixes": ["search-interface", "search-definition", "search-usage", "search-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_search_query = {
    # search-general
    "ilibtbsearch": "search-general",
    "libtbsearchmodule": "search-general",
    "lib-tb-search": "search-general",
    "buscar": "search-general",
    "busqueda": "search-general",
    "search": "search-general",
    # search-template
    "buscar con template": "search-template",
    "buscar y template": "search-template",
    "buscar + template": "search-template",
    "buscar más template": "search-template",
    "buscar mas template": "search-template",
    "buscar con templates": "search-template",
    "buscar y templates": "search-template",
    "buscar + templates": "search-template",
    "buscar más templates": "search-template",
    "buscar mas templates": "search-template",
    "template y buscar": "search-template",
    "template en buscar": "search-template",
    "template con buscar": "search-template",
    "template de buscar": "search-template",
    "template del buscar": "search-template",
    "template + buscar": "search-template",
    "template más buscar": "search-template",
    "template mas buscar": "search-template",
    "templates en buscar": "search-template",
    "templates con buscar": "search-template",
    "templates de buscar": "search-template",
    "templates del buscar": "search-template",
    "templates + buscar": "search-template",
    "templates más buscar": "search-template",
    "templates mas buscar": "search-template",
    "busqueda con template": "search-template",
    "busqueda y template": "search-template",
    "busqueda + template": "search-template",
    "busqueda más template": "search-template",
    "busqueda mas template": "search-template",
    "busqueda con templates": "search-template",
    "busqueda y templates": "search-template",
    "busqueda + templates": "search-template",
    "busqueda más templates": "search-template",
    "busqueda mas templates": "search-template",
    "template y busqueda": "search-template",
    "template en busqueda": "search-template",
    "template con busqueda": "search-template",
    "template de busqueda": "search-template",
    "template del busqueda": "search-template",
    "template + busqueda": "search-template",
    "template más busqueda": "search-template",
    "template mas busqueda": "search-template",
    "templates en busqueda": "search-template",
    "templates con busqueda": "search-template",
    "templates de busqueda": "search-template",
    "templates del busqueda": "search-template",
    "templates + busqueda": "search-template",
    "templates más busqueda": "search-template",
    "templates mas busqueda": "search-template",
    "search con template": "search-template",
    "search y template": "search-template",
    "search + template": "search-template",
    "search más template": "search-template",
    "search mas template": "search-template",
    "search con templates": "search-template",
    "search y templates": "search-template",
    "search + templates": "search-template",
    "search más templates": "search-template",
    "search mas templates": "search-template",
    "template y search": "search-template",
    "template en search": "search-template",
    "template con search": "search-template",
    "template de search": "search-template",
    "template del search": "search-template",
    "template + search": "search-template",
    "template más search": "search-template",
    "template mas search": "search-template",
    "templates en search": "search-template",
    "templates con search": "search-template",
    "templates de search": "search-template",
    "templates del search": "search-template",
    "templates + search": "search-template",
    "templates más search": "search-template",
    "templates mas search": "search-template",
    # search-theme
    "buscar y variables css": "search-theme",
    "buscar + variables css": "search-theme",
    "buscar mas variables css": "search-theme",
    "buscar más variables css": "search-theme",
    "variables css del buscar": "search-theme",
    "variables css y buscar": "search-theme",
    "variables css + buscar": "search-theme",
    "variables css mas buscar": "search-theme",
    "variables css más buscar": "search-theme",
    "variables css del componente buscar": "search-theme",
    "variables css y componente buscar": "search-theme",
    "variables css + componente buscar": "search-theme",
    "variables css mas componente buscar": "search-theme",
    "variables css más componente buscar": "search-theme",
    "busqueda y variables css": "search-theme",
    "busqueda + variables css": "search-theme",
    "busqueda mas variables css": "search-theme",
    "busqueda más variables css": "search-theme",
    "variables css del busqueda": "search-theme",
    "variables css y busqueda": "search-theme",
    "variables css + busqueda": "search-theme",
    "variables css mas busqueda": "search-theme",
    "variables css más busqueda": "search-theme",
    "variables css del componente busqueda": "search-theme",
    "variables css y componente busqueda": "search-theme",
    "variables css + componente busqueda": "search-theme",
    "variables css mas componente busqueda": "search-theme",
    "variables css más componente busqueda": "search-theme",

    "search y variables css": "search-theme",
    "search + variables css": "search-theme",
    "search mas variables css": "search-theme",
    "search más variables css": "search-theme",
    "variables css del search": "search-theme",
    "variables css y search": "search-theme",
    "variables css + search": "search-theme",
    "variables css mas search": "search-theme",
    "variables css más search": "search-theme",
    "variables css del componente search": "search-theme",
    "variables css y componente search": "search-theme",
    "variables css + componente search": "search-theme",
    "variables css mas componente search": "search-theme",
    "variables css más componente search": "search-theme",
    "search css variables": "search-theme",
    "search component css variables": "search-theme",
    "css variables search component": "search-theme",
}