# agent: { description, prefixes }
component_mapping_image_agent = {
    "image-general": { # Nombre de Agente
        "description": "Consultas sobre componente image",
        "prefixes": ["image-interface", "image-definition", "image-usage"] # Nombre de archivos .md a consultar
    },
    "image-template": { # Nombre de Agente
        "description": "Consultas sobre componente image y sus templates",
        "prefixes": ["image-interface", "image-definition", "image-usage", "image-template"] # Nombre de archivos .md a consultar
    },
    "image-theme": { # Nombre de Agente
        "description": "Consultas sobre las variables css del componente image",
        "prefixes": ["image-interface", "image-definition", "image-usage", "image-theme"] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_image_query = {
    # image-general
    "ilibtbimage": "image-general",
    "libtbimagemodule": "image-general",
    "lib-tb-image": "image-general",
    "imagen": "image-general",
    "image": "image-general",
    # image-template
    "imagen con template": "image-template",
    "imagen y template": "image-template",
    "imagen + template": "image-template",
    "imagen más template": "image-template",
    "imagen mas template": "image-template",
    "imagen con templates": "image-template",
    "imagen y templates": "image-template",
    "imagen + templates": "image-template",
    "imagen más templates": "image-template",
    "imagen mas templates": "image-template",
    "template y imagen": "image-template",
    "template en imagen": "image-template",
    "template con imagen": "image-template",
    "template de imagen": "image-template",
    "template + imagen": "image-template",
    "template más imagen": "image-template",
    "template mas imagen": "image-template",
    "templates en imagen": "image-template",
    "templates con imagen": "image-template",
    "templates de imagen": "image-template",
    "templates + imagen": "image-template",
    "templates más imagen": "image-template",
    "templates mas imagen": "image-template",
    "image con template": "image-template",
    "image y template": "image-template",
    "image + template": "image-template",
    "image más template": "image-template",
    "image mas template": "image-template",
    "image con templates": "image-template",
    "image y templates": "image-template",
    "image + templates": "image-template",
    "image más templates": "image-template",
    "image mas templates": "image-template",
    "template en image": "image-template",
    "template con image": "image-template",
    "template de image": "image-template",
    "template + image": "image-template",
    "template más image": "image-template",
    "template mas image": "image-template",
    "templates en image": "image-template",
    "templates con image": "image-template",
    "templates de image": "image-template",
    "templates + image": "image-template",
    "templates más image": "image-template",
    "templates mas image": "image-template",
    # image-theme
    "imagen y variables css": "image-theme",
    "imagen y variables css": "image-theme",
    "imagen + variables css": "image-theme",
    "imagen + variables css": "image-theme",
    "imagen mas variables css": "image-theme",
    "imagen mas variables css": "image-theme",
    "imagen más variables css": "image-theme",
    "imagen más variables css": "image-theme",
    "variables css del imagen": "image-theme",
    "variables css del imagen": "image-theme",
    "variables css y imagen": "image-theme",
    "variables css y imagen": "image-theme",
    "variables css + imagen": "image-theme",
    "variables css + imagen": "image-theme",
    "variables css mas imagen": "image-theme",
    "variables css mas imagen": "image-theme",
    "variables css más imagen": "image-theme",
    "variables css más imagen": "image-theme",
    "variables css del componente imagen": "image-theme",
    "variables css del componente imagen": "image-theme",
    "variables css y componente imagen": "image-theme",
    "variables css y componente imagen": "image-theme",
    "variables css + componente imagen": "image-theme",
    "variables css + componente imagen": "image-theme",
    "variables css mas componente imagen": "image-theme",
    "variables css mas componente imagen": "image-theme",
    "variables css más componente imagen": "image-theme",
    "variables css más componente imagen": "image-theme",
    "image y variables css": "image-theme",
    "image y variables css": "image-theme",
    "image + variables css": "image-theme",
    "image + variables css": "image-theme",
    "image mas variables css": "image-theme",
    "image mas variables css": "image-theme",
    "image más variables css": "image-theme",
    "image más variables css": "image-theme",
    "variables css del image": "image-theme",
    "variables css del image": "image-theme",
    "variables css y image": "image-theme",
    "variables css y image": "image-theme",
    "variables css + image": "image-theme",
    "variables css + image": "image-theme",
    "variables css mas image": "image-theme",
    "variables css mas image": "image-theme",
    "variables css más image": "image-theme",
    "variables css más image": "image-theme",
    "variables css del componente image": "image-theme",
    "variables css del componente image": "image-theme",
    "variables css y componente image": "image-theme",
    "variables css y componente image": "image-theme",
    "variables css + componente image": "image-theme",
    "variables css + componente image": "image-theme",
    "variables css mas componente image": "image-theme",
    "variables css mas componente image": "image-theme",
    "variables css más componente image": "image-theme",
    "variables css más componente image": "image-theme",
    "image css variables": "image-theme",
    "image component css variables": "image-theme",
    "css variables image component": "image-theme",
}